### ISSUE TITLE
Virtualmin Git: No button clicked

### ISSUE THREAD

**Issue by recursosformacion** [qooob/authentic-theme#546] opened 2016-09-08 17:58 UTC
Another time!:
When the Virtualmin Git plugin is installed, clicking on "Repository Commands" or "Browse Repository" it will display an error page with the message: "No button clicked!"

 I used version 5.02

**Comment by qooob** [comment] 2016-10-15 14:47
It was global bug produced by something I wouldn't think to exist (caused by server-side).

It will be fixed in 18.20. Thanks for reporting.

**Closed by qooob** 2016-10-15 14:47 UTC
Labels: bug

**Comment by qooob** [comment] 2016-10-29 20:32
Version 18.20 is out, please upgrade.
