### ISSUE TITLE
System logs character encoding

### ISSUE THREAD

**Issue by neubreed** [qooob/authentic-theme#465] opened 2016-05-23 01:22 UTC
My language is set to en.UTF-8 but I'm getting encoded strings for < and > while looking through system logs module..  see example below:

`
postfix/smtp[17142]: E50442F105: to=&lt;www-data@virt.test.com&gt;, relay=none, delay=31, delays=0.02/0/31/0, dsn=4.4.1, status=deferred (connect to virt.test.com[69.172.200.109]:25: Connection timed out)
May 20 03:16:12 nova postfix/qmgr[20786]: E50442F105: from=&lt;&gt;, size=44833, nrcpt=1 (queue active)
`

**Comment by qooob** [comment] 2016-05-23 09:02
Hi, 

This is the dupe of https://github.com/qooob/authentic-theme/issues/460

Will be fixed in 18.00 soon.

**Closed by qooob** 2016-05-23 09:02 UTC
