### ISSUE TITLE
Theme: Dasboard pie-charts are broken in Firefox nightly version

### ISSUE THREAD

**Issue by Jan02** [qooob/authentic-theme#670] opened 2017-03-09 16:45 UTC
* What is your server-side OS and its version? 
ubuntu server 16.04

* What is your client-side OS, browser and its versions?
Name: Firefox
Version: 55.0a1
Build ID: 20170309030216
Update Channel: nightly
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
OS: Windows_NT 10.0
Multiprocess Windows: 1/1 (Enabled by default)

* What are the steps to reproduce the issue

1. install webmin 1.831
2. open webmin dashboard with firefox nightly
3. result is 
![Image](https://framapic.org/SxeGvUlPxZyo/TPNOt52WClQO)
![Image](https://framapic.org/n2nEkfmTEkXh/9EmoY6fFHuPo)

**Comment by qooob** [comment] 2017-03-09 17:09
Hi,

What makes you think, that it's not the Firefox bug itself? If you go to the Piechart website, do they also look that?

**Comment by Jan02** [comment] 2017-03-09 17:12
what piechart website?

**Comment by qooob** [comment] 2017-03-09 18:45
http://rendro.github.io/easy-pie-chart/

**Comment by Jan02** [comment] 2017-03-09 22:25
the pie charts display correctly at that address

**Comment by qooob** [comment] 2017-03-10 10:16
Hi,

I have installed Firefox Nightly 55 version. Did testing.

I can't reproduce an issue. It's either on your side or been fixed in the night. :smile: 

Have a look at :video_camera: [videoscreencast](https://rostovtsev.ru/pub/src/authentic/18.40b/firefox-nightly_working_pie_charts.webm).

However, after writing the above, I started to doubt and thought that maybe distro version has it and it was fixed in my development. No, on my side version 18.32 works fine as well.

---

My guess is that you have problems with accelerations. Try going to Firefox options and disable it. Other than that, I have no idea, how this can be a fixable issue.

**Closed by qooob** 2017-03-10 10:16 UTC
