### ISSUE TITLE
Virtualmin SVN: Error when deleting repo

### ISSUE THREAD

**Issue by nabab** [qooob/authentic-theme#556] opened 2016-09-30 02:30 UTC
In Authentic Theme 18.10, when using Virtualmin SVN (URL/virtualmin-svn/), clicking the DELETE button in the repositories' list brings an error screen saying "No button clicked!"
With the framed skin the same action works fine.

**Comment by qooob** [comment] 2016-09-30 07:33
Hi,

I will take a look and fix it in 18.20.

**Comment by qooob** [comment] 2016-10-15 14:48
It was global bug produced by something I wouldn't think to exist (caused by server-side).

It will be fixed in 18.20. Thanks for reporting.

**Closed by qooob** 2016-10-15 14:48 UTC

**Comment by qooob** [comment] 2016-10-29 20:33
Version 18.20 is out, please upgrade.

**Comment by rwakcjr** [comment] 2018-03-07 15:01
I know this thread is closed, but I have the similar problem, because all of the buttons return "No button clicked!" and it also works when I choose the old theme.

Operating system | CentOS Linux 7.4.1708
Webmin version | 1.880
Usermin version | 1.734
Virtualmin version | 6.02 
Theme version | Authentic Theme 19.09.2
Kernel and CPU | Linux 3.10.0-693.17.1.el7.x86_64 on x86_64
