### ISSUE TITLE
SMART Drive Status: Won't scroll back up

### ISSUE THREAD

**Issue by BenchPressesBooks** [qooob/authentic-theme#561] opened 2016-10-14 19:17 UTC
When you access the SMART Drive Status module in webmin it will automatically scroll to the bottom of the page as the hard disks go through their SMART diagnostic checks just as it always did. In this latest version of the theme once the last drive finishes it is not possible to scroll back up on the page. If you try to use the mouse wheel or the scroll bar the screen jiggles and returns to the bottom. This is the same way with all 3 of my servers

Servers
Operating System: Ubuntu 14.04.1 LTS 64-bit
Webmin: 1.820
Authentic Theme: 18.10
Status SMART Drive Module Version: 1.820

Client
Windows 10 Professional x64 w. Anniversary update
Firefox 49.0.1
Internet Explorer 11.187.14393.0

**Comment by qooob** [comment] 2016-10-23 11:22
Does it happen in Firefox as well? IE 11 doesn't have full support.

Maybe you could post a screenshot, because I'm not sure how to reproduce an issue.

**Comment by qooob** [comment] 2016-10-23 11:43
I see now when this issue is happening. In options you checked `Display mode` to `Show All`. It will be fixed in 18.20.

Thanks for reporting.

**Closed by qooob** 2016-10-23 11:43 UTC

**Comment by qooob** [comment] 2016-10-29 20:33
Version 18.20 is out, please upgrade.
