### ISSUE TITLE
Copying SSL cert to Webmin copies to usermin

### ISSUE THREAD

**Issue by DJSADERS** [qooob/authentic-theme#651] opened 2017-01-19 09:11 UTC
Hi,

When i click copy to webmin on any SSL Certificate is copies is to usermin.
It's possible to manually go into webmin and point it to the certificate, but i'm pretty sure thats not how it's supposed to work. :)

**Comment by qooob** [comment] 2017-01-19 09:34
Hi,

This is not the theme issue dupe of https://github.com/qooob/authentic-theme/issues/625

Did you update your Webmin? If you did and have the latest 1.831 make sure to submit an issue to [Webmin Issue Tracker](https://github.com/webmin/webmin/issues)

**Closed by qooob** 2017-01-19 09:34 UTC
