### ISSUE TITLE
File Manager: Internet Explorer 11 loop on first load

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#818] opened 2017-06-25 10:49 UTC
See thread here: https://www.virtualmin.com/node/52621

Copy-pasted for convenience:

I noticed that there are two problems in the recent version.

    The virtualhost list combo box often does not appear. Especially in ie11(korean). It works well in Chrome.

    Others / File manager in ie11 (Korean), the Folder List will repeat indefinitely. It works well in Chrome.

We mainly use IE11.

If you have any answers, please let me know.

CentOS 6.9
webmin 1.844 virtualmin 5.99 Authentic Theme 18.49-8

**Comment by qooob** [comment] 2017-06-25 11:22
Alright, I will have to take a look. Thanks, Joe.

**Comment by humansoft** [comment] 2017-06-26 10:25
How are you.
Thank you for your interest.
I expect a good results.
Best regards.

**Comment by qooob** [comment] 2017-06-26 16:51
I'm aware about File Manager looping on the first load. I have no solution for this branch of the theme (18.xx) to solve this issue. It's only happening in Internet Explorer 11 and looks more like its inner bug rather than a theme bug. Here is why I think that: 

> However, before I made any changes to the code, after I opened console in IE, and run File Manager again from the left menu - the looping had disappeared. :beetle:

About dropdown in Virtualmin - I can't reproduce it. I have proper select arrow down displayed anytime I click around. How could I reproduce it?

I have tested it in _MIE11 11.1198.14393 (11.0.42)_ version and the File Manager bug was there. Will see what happens with the version _11.0.9600.18697 (11.0.43)_ after update.

I stand strong against using MSIE and try using at least MSEDGE browser or Chromium at best.

@humansoft Could you tell me sacredly, why are you using IE11?

**Comment by qooob** [comment] 2017-06-26 17:26
_11.0.43_ is till loop reloading File Manager unless console was opened at least once.

**Comment by humansoft** [comment] 2017-06-29 07:10
Thank you.
I know that most Koreans use IE11.
About 80~90%.
Best Regards.

**Comment by qooob** [comment] 2017-06-29 07:38
I think it should be much less. Browser [Market Share in South Korea](http://gs.statcounter.com/browser-market-share/all/south-korea). 

Nevertheless, I think it should be fixed. I just don't have a chance to do it right now. I am about to begin a complete rework of the theme as SPA (version 19). It will take time but going to bring user experience to completely new level.

Besides that, I'm personally still interested about your reason to use Internet Explorer over Chrome. Could you please tell me why?

**Comment by humansoft** [comment] 2017-06-30 04:36
Thank you.

I do not have the technical knowledge to compare IE and Chrome.

I simply think Chrome is less friendly than IE.

The Korean language displayed in Chrome is not natural.

I think Chrome has a weak page refresh feature,
The ability to refresh page is difficult in Chrome.
I think that the various  features are not included such as flash player and multi media function.

Also, I would like to inform you that many public and financial sites in Korea are optimized for IE.

Best Regards.

**Comment by qooob** [comment] 2017-09-26 11:57
Hi,

Due to raised complexity in the core code, there is no way it's possible to support _Internet Explorer 11_ any longer, starting from version 19.00.

_Microsoft_ itself recommends switching to new _Microsoft Edge_ browser, that will work just fine with new 19.00 release.

The numbers above can not be applied to Virtualmin community. In general, users that use Internet browser only for searching Google are drastically different from the people that are using webserver hosting panel.

It's very easy to start _Microsoft Edge_ instead of _Internet Explorer_ and get **better**, **safer** and **smoother** experience, unlike supporting dated and dying-out  technology.

-----

Starting from 19.00, the theme will produce a notice saying that things might and will be broken if using unsupported browser. _Google Drive_ and other _Google_ products produce such notifications and it's absolutely normal.

**Closed by qooob** 2017-09-26 11:57 UTC
Labels: bug

**Comment by BroxiNagil** [comment] 2017-12-14 16:09
How do you tell it's easy to start with Edge ? In my company we're at all limited to Win7/IE11 ! And as Win7 is in Support till 2020 it's a fault to stop supporting a Browser only for reason that your code got too complex ! I fully DISAGREE this decision !

**Comment by qooob** [comment] 2017-12-14 18:14
Hi,

It's all about market share, in other words users that are using it. I can't invest great amount of time and make the code that is harder to maintain for potentially only few users. There was the same situation about Internet Explorer 6 just few years ago. It kept back and created lots of mess for every single developer. Eventually everybody suffered - developers and most importantly users that were ready to use up to date technology and not always got it, as supporting dated browsers is utter mess and very time consuming. 

Please understand, I feel sorry for your situation. All I could recommend, is that you go and try to convince your company's technical support team, with raw facts (there are plenty of them), that using dated browsers is not solid, and potentially dangerous idea for eveybody. There is another obvious solution - install 18.49-49 package of the theme. You could always use Gray Theme while working from work and Authentic Theme from home.

I will not be able to invest time into Internet Explorer any more. Please understand.

**Comment by Zen4All** [comment] 2018-03-08 15:52
I do not agree with your reasoning about market share and ie6, as people then had the choice to upgrade to ie 7 or 8. If you are on windows 7 you can not upgrade to edge as you know, And ie6 was no longer supported by MS

Downgrading the theme version is also not an option, as I am not the only one using the server, but other people with different operating systems and browsers.
I am a fan of cutting edge technology, but you have to take care of existing tech too, as it is in common use all over the world.

This is the last will say about it, as it is obvious not going to change, but it is a big disappointment

**Comment by gnadelwartz** [comment] 2018-03-11 16:13
what about switching to grey framed themefor actual session  automatically if ie11- or older ff or older chrome  browser is detected? counts also for lynx or w3 terminal browsers

**Comment by qooob** [comment] 2018-03-11 16:24
Detection would have to be done on the server-side. Sounds like a feature request for Webmin.

**Comment by gnadelwartz** [comment] 2018-03-11 16:39
may be as combination:webmin ask theme do you support this browser string and fallback to grey theme if response is false ..

**Comment by gnadelwartz** [comment] 2018-03-11 16:57
done https://github.com/webmin/webmin/issues/859

**Comment by gnadelwartz** [comment] 2018-03-11 17:37
@Zen4All I can understand that ie11 is used in some environments. also my company switched to win10 but keep ie11 as default browser because of internally developed applications not running with edge or chrome 🙁

nevertheless the IT guys was smart enough to provide Firefox ESR for accessing internet.
it's very easy to install Firefox portable without admin rigths on every windows PC:
https://portableapps.com/apps/internet/firefox_portable

**Comment by Zen4All** [comment] 2018-03-11 20:23
@gnadelwartz I like the idea of the auto-detection. For me normally it is no problem to use other browsers, and am smart enough to find a solution 😄 , but my customers I have no control over.
It was not so much the incompatibility, but more the annoying message showing up at each mouse click..

I am glad you guys are looking in to a workaround. 👍  keep up the good work.
