### ISSUE TITLE
Settings / Default tab after logging in to Usermin - Bugged option

### ISSUE THREAD

**Issue by Stinkykiller** [qooob/authentic-theme#941] opened 2017-12-13 21:01 UTC
* What is your server-side OS and its version?
CentOS Linux 7.4.1708 / Webmin 1.870 / Virtualmin 6.02 / Usermin 1.720

* What is your client-side OS, browser and its versions?
Win7 / FF / 57.0.2 (64-bit)

* What are the steps to reproduce the issue?

**Case 1:**
Authentic theme settings - Default pages:
Default tab after logging in to Webmin - Webmin
Default module for Webmin - empty
Default page for Virtualmin - empty
Default tab after logging in to Usermin - **Usermin**

After successful login i'm prompted with Usermin (def. tab Usermin).

**Case 2 (bugged)**
Authentic theme settings - Default pages:
Default tab after logging in to Webmin - Webmin
Default module for Webmin - empty
Default page for Virtualmin - empty
Default tab after logging in to Usermin - **Mail**

After successful login i'm prompted with:
> Corrupted Content Error
> The site at https://mydomain.com:XXXXX/ has experienced a network protocol violation that cannot be repaired.
> The page you are trying to view cannot be shown because an error in the data transmission was detected.
> Please contact the website owners to inform them of this problem.

This is what i have in Usermin logs:
```
readline() on closed filehandle $ADDRESS at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 166.
Use of uninitialized value in split at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 600.
Use of uninitialized value $file in substitution (s///) at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 667.
Use of uninitialized value $file in substitution (s///) at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 668.
Use of uninitialized value $file in substitution (s///) at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 670.
Use of uninitialized value $mailbox::config{"server_name"} in string eq at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 1323.
Use of uninitialized value $mailbox::config{"server_name"} in string eq at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 1335.
Use of uninitialized value $mailbox::config{"server_name"} in string eq at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 1335.
```

Reloading the page will remove this error and open Usermin but the default tab didnt change and Usermin tab will be first to show up.

If i move back **Default tab after logging in to Usermin** to **Usermin** the problem is gone.

**Comment by Stinkykiller** [comment] 2017-12-13 21:13
Additional info:
I cant 100% confirm this but looks like the option **Default tab after logging in to Usermin** resets with each theme update. I'm sure that this option was set to **Mail** and i did this more than twice. First time when i changed to **Mail** i was not sure if i touched this option after the initial install (it was long time ago). Second time when Usermin changed default tab (Mail) back to **Usermin** was after the update (cant remember what version). But this didnt bother me too much as i have Virtualmin installed only on my test VPS, so i'm the only one using it. Now after few updates this option again reverted back to **Usermin** but this time when i change to Mail its causing earlier mentioned problem.

Sorry i cant provide more info but i'm not actively using this server and most of the time i just jump in for quick software updates and thats it.

**Comment by qooob** [comment] 2017-12-13 21:45
Hi,

I will take a look tomorrow morning. 

Tell me, what is Webmin 1.879? We just got out 1.870? Is this a  typo on your end?

**Comment by Stinkykiller** [comment] 2017-12-13 22:46
> Tell me, what is Webmin 1.879? We just got out 1.870? Is this a typo on your end?
Yes, my mistake. Probably i hit 9 instead of 0.

**Comment by qooob** [comment] 2017-12-14 18:58
Hi,

> I cant 100% confirm this but looks like the option Default tab after logging in to Usermin resets with each theme update.

This option can not be reset after update, because update doesn't touch files responsible for storing theme configurations. At least theme update and I believe Webmin update as well.

> Default tab after logging in to Usermin

About your issue with an error after login. I have installation of exact version of CentOS and I just tried to reproduce an issue and I couldn't.

Please take a look at [video-screencast](https://rostovtsev.ru/pub/src/authentic/19.04/usermin_goto_mail_tab_after_login.webm) of how it works on my side.

The errors in logs don't show a single sign of theme issue. It looks more like broken installation or mis-configuration on your side.

On my production server I have Usermin 1.721 already, maybe updating it will help.  Please tell me more if you wish but I'm closing this issue for now.

**Closed by qooob** 2017-12-14 18:58 UTC

**Comment by Stinkykiller** [comment] 2017-12-14 21:51
I installed Virtualmin before 2 or 3 years and aside of normal updates i didnt change much, especially Usermin. Even the Usermin settings are same as per default after the installation, so if something broke Usermin must be one of last few updates. Is there any way to check what part could be bugged, Usermin or your theme? I check all logs (not just Usermin) and no where to find any trace of this problem.

**Comment by Stinkykiller** [comment] 2017-12-14 22:18
Ok i have few more details i manage to dig out:
Error "Corrupted Content Error" is caused in FF when there are some conflicts with HTTP redirects. Tested this with Opera and no error so obviously FF have more strict rules. Plus when i used Opera i was able to login without any problem but the default tab was Usermin and not Mail. So something with redirects doesnt work when switched to "Mail" tab as default. Could this be some problem with your theme, at least in my installation?

**Comment by qooob** [comment] 2017-12-15 08:36
At first new [Usermin 1.730](http://webmin.com/index.html) is out. It addresses issues with redirects and latest theme.
https://github.com/webmin/webmin/issues/721#issuecomment-351866778

I tried all combinations that you described and I couldn't reproduce it. 😞 

Come on, upgrade to the latest Usermin. It just should work.

**Comment by Stinkykiller** [comment] 2017-12-15 12:15
I would upgrade if i have that option. Right now on Centos 7 there isnt any update for Usermin or any other *Min product, e.g. everything is updated.

**Comment by qooob** [comment] 2017-12-15 12:19
You could go with:

```Bash
yum update https://download.webmin.com/devel/rpm/usermin-1.730-1.noarch.rpm
```

**Comment by Stinkykiller** [comment] 2017-12-23 02:12
Not sure if this is still relevant information but looks like my problem is directly connected with another [bug](https://www.virtualmin.com/node/54735):
`HTTP/1.0 500 Perl execution failed Server: MiniServ/1.730 Date: Tue, 19 Dec 2017 00:26:51 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

Undefined subroutine &main::embed_noscript called at /usr/libexec/usermin/authentic-theme/authentic-lib.pm line 1692. `

Commenting out that line resolve both problems.

**Comment by qooob** [comment] 2017-12-23 09:53
Please install latest version of the theme using `update-theme.sh` script.

This issue is not possible to happen. `embed_noscript()` is there.
