### ISSUE TITLE
Core: Issues with Webmin v1.800 and SSLeay library

### ISSUE THREAD

**Issue by stuartxt** [qooob/authentic-theme#469] opened 2016-05-26 05:41 UTC
![screen shot 2016-05-26 at 15 33 49](https://cloud.githubusercontent.com/assets/13581186/15564701/4c03b772-2358-11e6-935e-50ddd882d74d.png)

I have just installed v 1.8 on a couple of servers and am now getting problems.

Ubuntu 12.04

Can't locate auto/Net/SSLeay/set_tlsext_.al in @INC (@INC contains: authentic-theme/lib /usr/share/webmin /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl . /usr/share/webmin/ ..) at /usr/share/webmin/web-lib-funcs.pl line 7350

**Comment by andreychek** [comment] 2016-05-26 05:50
Hmm, I don't seem to be seeing that issue myself with Webmin 1.80 and Ubuntu 12.04.

One thing you may want to try is to restart the Webmin service, and then reload the browser.

If you still get the issue after that, does it go away after switching back to the Virtualmin Framed Theme? Or do you continue seeing the issue?

**Comment by andreychek** [comment] 2016-05-26 06:03
Hmm, I did manage to get that output in another function though... but where I saw it wasn't theme related.

What you may want to do is file this as a bug report over at virtualmin.com, where Jamie could take a closer look in case it's more of a Webmin issue than a theme issue.

**Comment by stuartxt** [comment] 2016-05-26 06:13
I have it across four servers. All have been rebooted but still exists.

I have reverted back to the standard Webmin theme with no apparent issue.

I have also reported to the problem to Jamie.

**Comment by viruhost** [comment] 2016-05-26 06:16
Centos is the same problem

**Comment by qooob** [comment] 2016-05-26 06:29
It doesn't seem theme related. We're working on releasing fixed version.

**Comment by qooob** [comment] 2016-05-26 06:50
Meanwhile, you could safely downgrade to previous version of Webmin but make sure to disable `Security Alerts` (theme settings) on all servers. It has possible issue there since 17.81.

Will be fixed in version 18.00

**Comment by pdeleonardis** [comment] 2016-05-26 08:22
same problem also Ubuntu 12.04 Webmin 1.8

**Comment by qooob** [comment] 2016-05-26 09:38
It will be fixed in hours, when US wakes up.

Theme 18.00 is rolling out in minutes. Make sure to upgrade as soon as possible.

**Comment by qooob** [comment] 2016-05-26 11:45
Theme Version 18.00 please upgrade as soon as possible!

**Comment by qooob** [comment] 2016-05-26 11:46
Theme Version 18.00 is out - please upgrade as soon as possible!

**Comment by medariox** [comment] 2016-05-26 13:36
@qooob 
I have the exact same issue with Webmin 1.800 and Authentic Theme 18.00, running under CentOS Linux 6.7 with the latest available version of Net SSLeay (perl-Net-SSLeay-1.35-10.el6.x86_64) installed. The issue _seems_ to be caused by the Webmin 1.800 update and not by the Authentic Theme update. **Disabling the automatic updates** for the Authentic Theme _"solves"_ the issue.

**Comment by qooob** [comment] 2016-05-26 13:37
It solves this not because there is an issue in the theme but because the theme using SSLeay module when checking for the update. There is an error in Webmin 18.00 in this regard, which will be fixed soon by Jamie, I bet.

**Comment by georgesuba** [comment] 2016-05-26 14:41
seems to me that it does not happening on Debian 8.. been just trying to reproduce but without success. I  have automatic updates for authentic theme on.. tried this on all my servers with zero issues.

**Comment by stuartxt** [comment] 2016-05-27 03:26
I have applied the theme version 18.0 and also applied the webmin update 1.801.

All is working perfectly again, thanks for a great theme !

**Closed** 2016-05-29 11:08 UTC
Labels: bug
