### ISSUE TITLE
JS Edits not always firing in Usermin>File Manager

### ISSUE THREAD

**Issue by brianforan** [qooob/authentic-theme#722] opened 2017-04-21 18:47 UTC
Provide the following information:
* What is your server-side OS and its version?
Ubuntu 16.04
* What is your client-side OS, browser and its versions?
OSX Sierra, Chrome 57
* What are the steps to reproduce the issue
I'm not sure if this is a filemin issue or a theme issue but in the theme extension editor I have the code below. The purpose of the code is to hide certain folders/files based on page location to only visibly show files ending in certain extensions, such as `.xlsx`.

When I go to `Others > File Manager` and click that it has about a 25% chance of hiding the files, so I know it works sometimes but not all the time. Is this because of the way Webmin loads modules and it's not detecting? I have the function being called from both `$(document.ready(function () {})` as well as `$(document).ajaxSuccess(function() { })`. 

Edited out irrelevant code.

Code:

```js
function fileminCleanup() {
	if(window.location.href.indexOf(":20000") > -1 ) {
		$("#list_form tbody > tr").each(function() {
            if(!/(\.csv|\.doc|\.docx|\.xls|\.xlsx|>mnt<|>pd<|>hsx_[A-Za-z]*<)/.test($(this).html())) { 
               $(this).hide(); 
            }

        }) 
    } //end href if
}
```

**Comment by qooob** [comment] 2017-04-21 18:52
At the moment the current version of Filemin in Usermin is not compatible with the latest version of the theme 18.30+.

It will be fixed on the next release of Usermin. Jamie is ready to do it. Please wait a little longer. In case you still have an issue with it, please let me know.

I'm releasing 18.45 right now.

**Closed by qooob** 2017-04-21 18:52 UTC

**Comment by brianforan** [comment] 2017-04-21 18:53
Ok thanks, wasn't sure. Just to clarify though, that *should* fix it to work 100% of the time on page loads?

**Comment by brianforan** [comment] 2017-05-23 18:35
@qooob are there known issues with this despite the recent update? I've updated the theme for webmin/usermin from the github `./theme-update.sh` as well as updated webmin+usermin to recent versions but still experiencing this issue on most page loads, file uploads.

**Comment by qooob** [comment] 2017-05-23 18:40
What is your Usermin version?

**Comment by brianforan** [comment] 2017-05-23 18:43
1.710

**Comment by qooob** [comment] 2017-05-23 18:44
Just reload the whole page using `Ctrl+Shift+R`.

Try incognito mode or the other browser. It's stuck cache. Anytime I reload the browser and it's cache it went away.

**Comment by brianforan** [comment] 2017-05-23 18:52
I'll try another browser, but I went in as incognito and it *somewhat* worked. The login page was missing our icon and some other theme settings. Everything was good until I got to my desired $PATH and reloaded page from a hard refresh (should trigger `$(document).ready()`?) and then it didn't work.

Some scripts are working, but the one from the original post at the top is still not working. Also, it does not seem to trigger  on file upload either when the page is loaded.

I can share my code with you if you think it'd help diagnose, there are no errors in dev console but I can try adding some debuggers in. The code is just a bunch of functions that are visual changes since usermin is being used for end users we need it to be as simplified as possible, and then I take those functions in call them in two blocks like so:

```
$(document).ready(function() {
    allCleanup();
	if(window.location.href.indexOf(":20000") > -1) {
    	   forceFilemin(); //forces screen to file manager
           userminCleanup(); //visual usermin changes
           fileminCleanup(); //removes some drop downs and should hide files but only removes dropdowns when it doesnt work
          putDirections(); //directions for using file manager (for end users, it just overwrites one of the elements under the file manager)
    }	
});

$(document).ajaxSuccess(function() {
	if(window.location.href.indexOf(":20000") > -1) {
            forceFilemin();
            fileminCleanup();
            userminCleanup();
            putDirections();
        }
});
```

**Comment by qooob** [comment] 2017-05-23 18:55
What is this code? Is it what you add to extensions?

I'm not sure what is not working for you.

**Comment by brianforan** [comment] 2017-05-23 19:01
Yes, it's added in theme extensions and I check if `:20000` is in the url because I only want these changes to affect Usermin.

This code below is meant to hide certain file types (like in OP) and also hide some other drop downs. Really the most important part is to hide the file types from the regex but that is what is not firing on some page loads, even though part of the function is actually working:
```
function fileminCleanup() {
	if(window.location.href.indexOf(":20000") > -1) {
        
        //Hide option to make new tabs - don't remove.
        $("#file-manager-new-instance").remove();
        
        //Hide any files that don't atch the specified file types, or if they are folder in the `/mnt/pd/abc_` path
		$("#list_form tbody > tr").each(function() {	
    		if(!/(\.csv|\.doc|\.docx|\.xls|\.xlsx|>mnt<|>pd<|>abc_[A-Za-z]*<)/.test($(this).html()))
    		{ 
            	$(this).hide(); 
    		}
		});	

		//clean up drop downs to only include create new file
        $("body.filemin.file-manager div.btn-group.pull-right ul[aria-labelledby*=dropdownMenu] li").each(function() {
        	if($(this).html().toLowerCase().indexOf("upload to current directory") > -1) {
            	return true; //leave this one
            } else {
            	$(this).remove();  
            }
        });
        
        //remove drop downs that don't matter
        $("body.filemin.file-manager div.btn-group.pull-right button").each(function() {
        	if($(this).html().toLowerCase().indexOf("file") > -1) {
            	return true;
            } else if($(this).html().toLowerCase().indexOf("fa-refresh") > -1) {
            	return true;
            } else if($(this).html().toLowerCase().indexOf("fa-trash") > -1) {
            	return true;
        	} else {
            	$(this).remove();
            }
        });
   } }
```

**Comment by brianforan** [comment] 2017-05-23 19:02
Hope that makes more sense, thanks for the help

**Comment by qooob** [comment] 2017-05-23 22:36
The problem is that dataTables (DT) draw's function run each time the table changes. Looking at your code makes me think that it would only hide things upon first load?

It's not gonna be easy to achieve as the core code isn't meant to be extensible like this at the moment.

Hiding menus is probably alright but what about the hotkey? User can always click the hotkey? 

I really not sure why you're trying to cut-off functionality like this.

It seems to me like this "security via obscurity" is not secure at all.

**Comment by brianforan** [comment] 2017-05-24 13:20
I do agree with you about the "security via obscurity" but it's more of hiding against accidents rather than malicious attacks. After all, I don't think using client sided code would ever be considered a security best practice anyway. Not too worried about the hot key. If someone ends up using a hot key then so be it, or I guess I could just throw listeners in there and just return false.

The draw function must work on ajax because the `$().ajaxSuccess()` picks up most changes, and sometimes fixes ones that weren't caught.

We went with webmin/usermin for this usage because of its ease of use specifically with privacy because of the need for HTTPS and authenticating Unix users directly, also your theme makes it a lot more attractive for everyday end users and back end alike.

**Comment by brianforan** [comment] 2017-05-24 13:30
Would it be feasible to use dataTable's `drawCallback`? Only downside is the datatable creation is on the server I believe..

**Comment by qooob** [comment] 2017-05-24 17:44
> Would it be feasible to use dataTable's drawCallback

It would be possible but it will be difficult to do. 

No, dataTables runs on the client-side.
