### ISSUE TITLE
Virtualmin: System Statistics has no graphs

### ISSUE THREAD

**Issue by UTCWebDev** [qooob/authentic-theme#386] opened 2016-02-13 15:28 UTC
This feature works in Virtualmin Framed Theme, but not Authentic.
Macbook Pro OS X, Firefox, Chrome, Safari... none show the graphs.

**Comment by qooob** [comment] 2016-02-13 16:59
Hi,

There are two possible issues:

1. Non UTF-8 encoding - I have noticed that there are some encoding problems from your screenshot's title. (less-likely);
2. Some extensions that block _Statistics_ script, like add blocker.

Try to run it in incognito mode and check all over again (as far as I'm aware, in incognito mode, all plugins are off)

I can not reproduce your issue, have a look at my [video screencast](http://rostovtsev.ru/pub/src/authentic/17.65/working_VM_statistics_-_issue_386.webm) that I just made.

**Comment by UTCWebDev** [comment] 2016-02-13 18:52
Private mode in Safari, FF, FFDeveloperEdition reveal the encoding error in the title, and do not show the graphs. Switching to Virtualmin Framed Theme displays correct title and also displays graphs.

**Comment by qooob** [comment] 2016-02-13 18:54
Set encoding correctly: [Troubleshoot](https://github.com/qooob/authentic-theme#troubleshoot)

Could you make video screencast with opened console in Chrome please?

**Comment by UTCWebDev** [comment] 2016-02-13 19:09
<img width="780" alt="screen-shot 2016-02-13 at 2 08 57 pm" src="https://cloud.githubusercontent.com/assets/2539685/13029477/6dfc549a-d25b-11e5-8d8e-91143e5ae421.png">

**Comment by qooob** [comment] 2016-02-13 19:25
Do _force update_ theme from theme settings and restart Webmin. Clear browser's cache. I don't see how this could be happening. In case nothing else helps, please restart your server.

**Comment by qooob** [comment] 2016-02-13 19:26
Try using you phone's browsers. You should not get this error. Did you see my screencast?

**Comment by qooob** [comment] 2016-02-14 14:25
Did you try other computer? You have Virtualmin Pro, right?

**Comment by UTCWebDev** [comment] 2016-02-14 15:01
I have tried with 3 different Macbook Pro computers, all running latest OS X, FF, Safari and Chrome.

I have tried with iOS iPad, same results: no statistics graphs.

Yes, this is Virtualmin Pro.

The UTF-8 Language setting did fix the text-editor "~A" on blank lines.

Safari console errors:

Unrecognized Content-Security-Policy directive 'child-src'.

onLoad - history.cgi:162
ReferenceError: Can't find variable: Timeplot
onLoadhistory.cgi:161
(anonymous function)authentic.min.js:5:284450

**Comment by qooob** [comment] 2016-02-14 17:22
Could you please provide video screencast, right after force upgrading the theme?

**Comment by qooob** [comment] 2016-02-14 17:23
I can not reproduce your issue on my Mac laptop.

**Comment by qooob** [comment] 2016-02-17 08:12
Any update on this one?

**Comment by UTCWebDev** [comment] 2016-02-17 15:39
Ilia, this must be a configuration problem specific to my server, if you cannot replicate. 

I have also tested on PC IE, Chrome, FF and the problems are the same. 

I do not want to post video screencast of the server.

I will report this in VM support tickets and will allow remote support assistance.

**Comment by qooob** [comment] 2016-02-17 17:41
I understand. I will be notified in case it's found out that it's my bad.

I will keep this issue closed, as I will not be able to assist any further. Feel free to open it in the future.

Are you having install VM 5.0? Did you try to reinstall VM?

**Comment by goranmitev** [comment] 2016-03-11 16:00
I just want to report that I have the same exact issue. I just switch the theme if I want to see historic statistics. 

Anyway, I'm using Ubuntu if that helps, with Virtualmin Pro.

**Comment by qooob** [comment] 2016-03-11 16:01
Do you get any errors on the console?

**Comment by qooob** [comment] 2016-03-11 16:19
I just tested it in Ubuntu - all is working on my side. :( I can't reproduce it yet..

**Comment by goranmitev** [comment] 2016-03-11 16:27
Yes there are errors. 

Here is a screenshot in Firefox: https://onedrive.live.com/redir?resid=263FE9C6BC9F0BDD!14705&authkey=!ANAkYttJrW99-Zg&v=3&ithint=photo%2cpng

Here is a screenshot in Chrome: https://onedrive.live.com/redir?resid=263FE9C6BC9F0BDD!14707&authkey=!AAkHNlNeW0TKle0&v=3&ithint=photo%2cpng

I'm using Windows 10 btw. But the Virtualmin is on Ubuntu.

**Comment by UTCWebDev** [comment] 2016-03-11 17:02
Goran & Ilia, the character encoding issues in editor and titles are now OK, as are the dashboard gauges... no more NaN% for nonexistent swap memory, no more funny characters in titles or editors. However, the VM Pro System Statistics show same error for me via Mac Safari, Chrome, Firefox.
![screen-shot 2016-03-11 at 11 59 00 am](https://cloud.githubusercontent.com/assets/2539685/13709282/17d67cea-e781-11e5-86ff-265797373ebf.png)
![screen-shot 2016-03-11 at 11 58 11 am](https://cloud.githubusercontent.com/assets/2539685/13709284/19756b74-e781-11e5-836f-d2ba54991205.png)

**Comment by qooob** [comment] 2016-03-11 17:20
This is what I mean, when I say I can't reproduce it, not even in Safari.

http://rostovtsev.ru/pub/src/authentic/17.72/working_statistics.mp4

Guys, please use my Website to submit securely login credentials. I understand your concerns but I don't see how this could be happening.

Did you try to force re-install Virtualmin?

**Comment by UTCWebDev** [comment] 2016-03-11 19:14
Force-reinstall Virtualmin Pro is not really an option on a live public system, if I recall correctly.

Ilia, your screencast video looks like you are not running https? Could that be the issue with Content security policy: couldn't process unknown directive 'child-src'?

**Comment by qooob** [comment] 2016-03-11 20:32
`child-src` directive comes from Webmin 17.50+, as far as I remember. However, I don't think it's the issue.

I would like to ask those having this issue to add me on qooob@jabbers.im (XMPP), so later, when we both have time, we could chat. I would ask few questions, while you could debug it online.

In regard of `http/https` - it's irrelevant, as I tested it in multiple ways, on multiple platforms.

In about 10 days, I will be fully dedicated to working on the theme again.

Reinstalling Virtualmin (only the package, whitout erasing configuration files), should be fine.

**Comment by swelljoe** [comment] 2016-03-11 21:05
Definitely don't force reinstall Virtualmin! I have absolute confidence that won't do anything good.

It's possible to verify the file contents of packages using RPM or apt, if we're concerned about it being files missing, but I don't think that's the problem here, though I'm not sure what is.

Is this a VPS of some sort? Is it possible memory isn't actually as available as is being reported? Sometimes weird things happen on OpenVZ/Virtuozzo systems when they are oversold. I imagine other virtualization types that allow overselling memory could have the same issues.

**Comment by swelljoe** [comment] 2016-03-11 21:07
Oh, I'm seeing this problem, too! I'm looking into it, and will loop Ilia in on the system that's exhibiting it if I don't see how to fix it myself.

**Comment by qooob** [comment] 2016-03-11 21:19
https://github.com/webmin/webmin/issues/262

**Comment by qooob** [comment] 2016-03-11 21:22
Rolling back to WM 1.760 could bring test results. Do it better on debug machine. However, if you know what you're doing, it should be alright anyway.

**Comment by swelljoe** [comment] 2016-03-11 23:14
Theme 17.54 does not exhibit the problem. 17.60 does. So, I'm guessing the new page loading code is the culprit.

Also, if I weren't swamped with website and ordering bugs, I would be looking at a new graphing library. There are numerous ones that are nicer than Timeplot, now, and would probably be more amenable to being loaded with AJAX requests and such (I ran into this same problem in my theme when I switched to a single page app, with page loads happening via JavaScript...I never figured out how to resolve it). Ilia is smarter than me though, so he'll probably be able to fix it. But, going forward, I think a new plotting library would be the smart thing.

**Comment by swelljoe** [comment] 2016-03-11 23:19
I guess the confusing thing is that Ilia isn't seeing it on his boxen, which has the latest theme. Whereas I see it on Chrome and Firefox, with and without the CSP header enabled in Webmin.

**Comment by UTCWebDev** [comment] 2016-03-11 23:51
Hey Joe,
My particular VM Pro box is an Amazon EC2 Instance... it behaves more like a dedicated server than a VM, in my experience, though the EC2 Security Groups firewall, networking and some I/O is different. 

Ports 80,443,10000,20000 are open to the world in my Security Groups, so I don't think its restricted at the crude edge firewall level. They are also open in ConfigServer Firewall, so there should not be any blocking there. The only time in the WWW world I ever see content restrictions is when a https page is trying to serve up a http src, webfoot, or css include... or when a https cert for an https remote asset has a self-signed or otherwise unacceptable cert.

I'm not too worried about the loss of Stats graphs, with all the other improvements of Authentic.

**Comment by GNUMatrix** [comment] 2016-03-12 00:03
Seeing the same problem.  Just updated to 17.72, no difference.  Using a different theme (Virtualmin frames) worked though, maybe that helps narrow the issue down a bit?

**Comment by qooob** [comment] 2016-03-12 03:52
Joe says it works on theme 17.54? Could anyone having this issue downgrade the theme to this point and check?

**Comment by qooob** [comment] 2016-03-12 04:15
Here is the link, please try:
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.64.wbt.gz

**Comment by UTCWebDev** [comment] 2016-03-12 09:35
Sure enough, stats work in 17.54:
![screen-shot 2016-03-12 at 4 32 55 am](https://cloud.githubusercontent.com/assets/2539685/13722219/c4c87bda-e80b-11e5-9e4d-bb842579379b.png)

**Comment by UTCWebDev** [comment] 2016-03-12 09:39
However, same console errors:
<img width="1261" alt="screen-shot 2016-03-12 at 4 39 35 am" src="https://cloud.githubusercontent.com/assets/2539685/13722235/765fa4b8-e80c-11e5-8da7-75be8a2db5df.png">

**Comment by swelljoe** [comment] 2016-03-12 09:44
The console errors were a red herring, and are merely warnings. It's possible to disable CSP headers in Webmin with the "no_content_security_policy=1" option in the Webmin configuration file (/etc/webmin/config, I think, or maybe it goes in /etc/webmin/miniserv.conf, I can't recall). But, it's not necessary unless you really hate the warnings. I think we'll converge on a correct set of CSP headers and browsers will get full CSP support eventually.

**Comment by UTCWebDev** [comment] 2016-03-12 16:07
adding that directive to /etc/webmin/config and webmin restart got rid of the warnings.

**Comment by qooob** [comment] 2016-03-12 16:09
..warnings? ..but it wouldn't make stats work with the latest theme version?

**Comment by UTCWebDev** [comment] 2016-03-12 16:11
Ilia, no. Security warnings are gone, but we still get Timeplot error:
ReferenceError: Can't find variable: Timeplot
onLoadhistory.cgi:161
(anonymous function)authentic.min.js:5:284284

**Comment by qooob** [comment] 2016-03-12 16:14
Ok, can you please be kind updating theme up, version by version.. Can you tell me which version it stops working:

https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.60.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.61.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.62.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.63.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.64.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.65.wbt.gz

https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.70.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.71.wbt.gz
https://github.com/qooob/authentic-theme/raw/master/.build/authentic-theme-17.72.wbt.gz

It's important for me to know where exactly it stopped working on your side.. as, like I already mentioned, it works for me all over..

**Comment by UTCWebDev** [comment] 2016-03-12 16:17
17.60 it does not work.

**Comment by qooob** [comment] 2016-03-12 16:20
I was just looking at my Changelog and I couldn't understand what could cause the issue..

**Comment by qooob** [comment] 2016-03-12 16:21
..that would work on 17.54 and not in 17.60..

**Comment by swelljoe** [comment] 2016-03-13 19:05
One more data point and an explanation for why Ilia isn't seeing the problem. When I check on localhost (same machine running Webmin and my browser), the graphs show up. This makes me think maybe it *is* some sort of security mechanism kicking in, and preventing timeplot.js.min from being loaded.

I've been reading the diffs from 17.54->17.60 and, so far, don't see why it's not working. But, will keep poking.

**Comment by qooob** [comment] 2016-03-13 19:08
Joe, that is interesting but it's not exactly the same machine. I run it on separate (second/the orher) machine but on the same local network.

**Comment by swelljoe** [comment] 2016-03-13 19:08
And, it is as simple as timeplot.min.js not being loaded. So, we just need to figure out why timeplot isn't being loaded and problem will be solved, I think.

**Comment by qooob** [comment] 2016-03-13 19:09
Joe, thanks, I'll take a loom.

**Comment by swelljoe** [comment] 2016-03-27 18:00
Hey Ilia, I've talked to Jamie about getting JSON output from the graphs data provider, and he's happy to work on that over the next day or two.

Perhaps we should look into switching to something like rickshaw (http://code.shutterstock.com/rickshaw/) or nvd3 (http://nvd3.org/examples/stackedArea.html). I think I like rickshaw best, and it has examples of realtime charts, so when we begin moving to realtime charting features it's probably easy to make it work with rickshaw. But both look nice, and both work with JSON data, so once we've made the graph data provider spit out JSON when requested, changing graph libraries wouldn't be terribly hard.

If you've wrapped up your other project for now, and can poke at Authentic again, I'd be able to work with you on getting that spinning. I'm sure the current graphs could be made to work somehow, but I think if we spent the time on a new graphing library, we'd end up with a better user experience for not a lot more effort.

**Comment by qooob** [comment] 2016-03-27 20:14
Hi, Joe!

I've looked at both and I think for live graphs Rickshaw seems to be the best.

I'm going to be fully available to start my work on Authentic on Tuesday morning or even tomorrow evening. I have finished few days ago another gigantic amount of work on Karateka, so now I'm feeling free and happy to continue with the theme.

Joe, if Jamie does JSON data supply, I probably will release 17.80 with the new graphs already and avoid annoying work with Timeplot. Do you think Jamie/you could do it?

**Comment by swelljoe** [comment] 2016-03-27 20:34
Yes! Jamie can add JSON support to the data provider within the next day or two. I will check in with him, but I suspect the implementation will simply be a query string ?format=json or similar, or he'll implement a new history_data_json.cgi type thing. Either would work for this.

I'll ask him to check in on this thread with his thoughts on how he'll implement JSON output for history_data.cgi

Maybe ideally, we should implement this directly in history.cgi in Virtualmin, rather than making it exclusive to Authentic. The work is a little bit JavaScript, a little bit HTML, and a little bit Perl...you're obviously the best among us at JavaScript and HTML, so e may need to coordinate a little bit to make all that happen.

**Comment by qooob** [comment] 2016-03-27 20:36
Sure, let's do it for all themes. I will be happy to help with it. Just let's get to work as mentioned above and see how to toss things up. ;)

**Comment by swelljoe** [comment] 2016-03-27 20:40
So, steps to completion, I think:

1. Jamie implements JSON output for history_data.cgi
2. You work up the HTML/JavaScript side of things that queries history_data.cgi and draws graphs.
3. I help you merge the HTML/JavaScript into an updated history.cgi, replacing timeplot with Rickshaw.
4. Somewhere down the road, we implement a live updates option that periodically queries history_data.cgi for more recent data and updates the graphs.

License for rickshaw is MIT, so it is compatible with the other licenses we have to interact with (and the same as the old Timeplot library), so I think we're all happy with Rickshaw.

**Comment by qooob** [comment] 2016-03-27 20:55
:+1: I'll wait for Jamie's implementations then, while fixing the list of issues and implementing new features for File Manager.

**Comment by jcameron** [comment] 2016-03-27 21:06
Sure, I can implement that. Just let me know roughly what format you'd like the JSON to be in.

**Comment by qooob** [comment] 2016-03-28 06:15
It would depend on the graphs we're working on. For System Statistics, I think [Example 06](http://code.shutterstock.com/rickshaw/tutorial/introduction.html) or [this one](http://code.shutterstock.com/rickshaw/examples/hover.html) would be the best.

From the [documentations](https://github.com/shutterstock/rickshaw):
**series**

>Array of objects containing series data to plot. Each object should contain data at a minimum, a sorted array of objects each with x and y properties. Optionally send a name and color as well. Some renderers and extensions may also support additional keys.

Example:
```JavaScript
[
	{
		data: [ { x: 0, y: 120 }, { x: 1, y: 890 }, { x: 2, y: 38 }, { x: 3, y: 70 }, { x: 4, y: 32 } ],
		color: "#c05020",
                name: "One"
	}, {
		data: [ { x: 0, y: 80 }, { x: 1, y: 200 }, { x: 2, y: 100 }, { x: 3, y: 520 }, { x: 4, y: 133 } ],
		color: "#30c020",
                name: "Two"
	}, {
		data: [ { x: 0, y: 200 }, { x: 1, y: 390 }, { x: 2, y: 1000 }, { x: 3, y: 200 }, { x: 4, y: 230 } ],
		color: "#6060c0",
                name: "Three"
	}
]
```

As seen, the JSON object has other value there. I think we should do other values passed using JavaScript, so technically it would be possible to make it optional in the future. This will require re-building the initial object to something that we need.

However, possibly it would be cool, if `history_data.cgi` could receive parameters and change data output. I think we need to enroll more graphs all over Webmin.

**Comment by jcameron** [comment] 2016-03-29 03:52
How about something like this :

`
[
  {
     data: [ { time: 1459223438, value: 555 }, { time: 1459223439, value: 677 }, { time: 1459223438, value: 558 } ],
     color: "#c05020",
     name: "CPU"
  }
]
`

**Comment by jcameron** [comment] 2016-03-29 03:55
The graph X axis has to be time, specified as a Unix timestamp.

**Comment by jcameron** [comment] 2016-03-29 04:14
I've checked in a change to `history_data.cgi` to support JSON output mode if called with `&json=1` - see https://github.com/virtualmin/virtualmin/commit/d13d7f64317f435e0a7542f8078d8891ae14a04e

**Comment by qooob** [comment] 2016-03-29 07:46
Look, good. I will come back to the Statistics very soon. There are some older bugs to fix first.

I'm thrilled with adding more graphs to Webmin.

**Comment by qooob** [comment] 2016-04-03 20:08
It will be fixed in 17.80.

Most likely by 17.90, there will be completely new graphs.

**Closed by qooob** 2016-04-03 20:08 UTC

**Comment by qooob** [comment] 2016-04-08 12:17
Please upgrade 17.80 is out!

**Comment by UTCWebDev** [comment] 2016-04-08 14:16
Hooray, statistics is working again.

**Comment by qooob** [comment] 2016-04-08 14:20
:) glad to hear.
