### ISSUE TITLE
Squid Analyzer Report Generator 

### ISSUE THREAD

**Issue by theAnDrO40** [qooob/authentic-theme#840] opened 2017-10-03 22:11 UTC
The Button "View Generated Report" has no function if push this button it will be only grayed thats all no function

i can push the button only after i have pushed the button above "Generate Report Now"

**Comment by qooob** [comment] 2017-10-04 09:21
Are you talking about http://squidlog.sourceforge.net ?

**Comment by qooob** [comment] 2017-10-04 09:49
I think I got it. It's the `sarg` command that is required for the module to show up. Looking in to it..

**Comment by qooob** [comment] 2017-10-04 11:13
I have this button 

![debug-debian_10000_sarg__xnavigation 1](https://user-images.githubusercontent.com/4426533/31172898-09e03d92-a90e-11e7-9cd3-ed963f0dc950.png)


and when I press it I'm taken here:

![debug-debian_10000_](https://user-images.githubusercontent.com/4426533/31172897-09dd34ee-a90e-11e7-82cd-110adb98bd7f.png)

Or there should be another button? Maybe it's not there because the file is empty?

**Comment by qooob** [comment] 2017-10-04 11:16
Okay, yes. I see what you mean. 

I'm looking for the cause of the problem.

**Comment by theAnDrO40** [comment] 2017-10-04 11:20
Yes okay there is a Button below Called „View generated Report“ after you generate the Report like you and you Go back to the module index and if you click on it then there will be no Action only the button is gray

**Comment by theAnDrO40** [comment] 2017-10-04 11:20
Ah okay thanks

**Comment by qooob** [comment] 2017-10-04 11:22
The reason why this is happening, just as in some other modules, is that the HTML for the page is not generated correctly. For example, this button is not inside of any form and thus can not be submitted properly.

I'll see what I can do and if it's possible to build global patch for all kind of case scenarios.

**Comment by theAnDrO40** [comment] 2017-10-04 11:27
That will be very nice because i have tested so many Themes and this is definitly the best and since the update to 19.00 i can use this theme on my iPad to manage my homeserver

**Comment by swelljoe** [comment] 2017-10-05 00:40
Let's fix the HTML. Don't work around it on the client-side.

**Comment by swelljoe** [comment] 2017-10-05 00:40
Make me a list of the cgis that have this problem, and I'll sit down and knock them all out in a day or two.

**Comment by qooob** [comment] 2017-10-05 06:20
I'm very happy to do it **not** on the theme side, in case it takes day or two. :wink: Let's start with this (even though I made a working and straight forward patch for it already) and previously discussed _Edit Cron Job_. It will be difficult to fix to make it work properly and look nice at the same time.

**Comment by swelljoe** [comment] 2017-10-05 11:26
Fixed with this patch: https://github.com/webmin/webmin/pull/645

I've made a pull request, so it can go into Webmin whenever Jamie's got time to make a new one.

**Comment by qooob** [comment] 2017-10-05 12:09
@theAnDrO40 Thank you very much for reporting bugs.

**Closed by qooob** 2017-10-05 12:09 UTC
