### ISSUE TITLE
Webmin/Virtualmin default tab doesn't work + general issues + speed

### ISSUE THREAD

**Issue by cmroanirgo** [qooob/authentic-theme#192] opened 2015-06-24 21:35 UTC
No matter the setting I use in "Default tab after logging in to Webmin", WebMin is always shown on the left hand side by default when I log into virtualmin (ubuntu 14.04). Is there some trick to make this work?
All the other themes default to VirtualMin for a reason. The main/right side then shows the default 

Also not working:
- change default virtualhost. It always shows the first one in my list

Also probably not working:
- Spinners. Everywhere are spinners. Waiting waiting waiting. This theme is exceedingly slow to load on each page load. 4.3secs for the home page, roughly 1.5secs to apply any page change. It is this reason, more than any other which causes me to prefer Finally or XenLayer Framed themes (which generally return the page nearly instantly).

**Comment by qooob** [comment] 2015-06-24 21:49
Default tab and default virtualhost should be working. Spinners were fixed in theme version starting 13.00 and it works same fast (0.5 sec.) in my all 3 systems with different OS.

System info page takes a long time, because it checks for updates and outgoing connection takes that long on your side - you can disable it in settings. There is no spinners really as it was before version 13, and anyway, you can disable it in settings.

There is a video overview and you can see the way theme should work.

I will double check default tab and virtualhost settings and let you know next week as I'm on vacation right now.

Meanwhile, tell me which browser/os you're using? Which theme version are you using? Latest, 13.05? Did you clear browsers cache after updating?

**Comment by cmroanirgo** [comment] 2015-06-24 22:16
I'm using chrome 43 (latest), osx 10.9 (mavericks), theme version 13.05, virtualmin/webmin 1.76 (just updated).
I've tested this on several ubuntu 14.04 boxes over the last few months (all VM's), and the result has always been the same. It's very sluggish, and the 'default tab' has never seemed to work.

I think we have very different ideas of 'speed'. 
Even looking at the video, for example 5:18 when using BIND editor, the page refreshes are not snappy. Perhaps it's all that animation stuff. I turned off the 'gauges' on the information page for that reason: I'd rather have nothing than have some 'pretty' animation wasting my time.
Perhaps I'd be happy with an option to turn off absolutely every animation. (eg nav bar slide ins, page fade in) perhaps this may affect how you approach any ajax requests being made too. 
My machines (either local, or remote) have ping times <10ms. Generally I would have a virtualmin page loaded and usable in <500ms. 

Nevertheless, regardless of any animations, here are some comparisons on initial page refresh times (Ctrl/Shift+F5, Cmd+R)
Authentic Theme: 4.3 secs
XenLayer Framed: 2 secs
Finally Theme: 2.5 secs

These times are relatively consistent, with maybe 300ms maximum variance. As you can see, I see an extra 2secs for Authentic...

Have a great holiday (sorry to disturb you... but you shouldn't be logging into github anyway!)

**Comment by qooob** [comment] 2015-06-25 08:28
OK! 

I will add an option in next release to disable animation on the left menu.

For some reason something tells me that ping ~10ms is horribly big for local machine. I'm at the sea now and having ping to my server that is in thousands km away around 50ms.. Ping for local should be around ~0.050ms..

Here is what we'll do. (I am at the laptop and can type now with ease)..

1. Go to theme settings. Set default page and tab and hit save button. Afterwards, in Chrome, click right mouse button on the right page (frame) and click `Reload Frame`. Now question: "Do you have selected options saved"?? In case they are not (this is what I believe is happening in you case) - you have to change the `chown/chmod` on the folder `/etc/webmin/authentic-theme` as `root:root` and `755`. In that folder you will find a file `settings.js`. It should be updated each time you save theme settings.

2. > Authentic Theme: 4.3 secs
That is not good and the only reason why it's happening because it takes a long time for your server to connect to GitHub - try running for server's console `ping raw.githubusercontent.com` to see the ping? What is it? I have 48ms from my server in Moscow (it's in DC). Like I said, from where I am now - it takes less than 2 seconds for me to see System Info Page of my server in Authentic Theme (and WiFi here is not the best on earth, that's for sure). In case settings work for you go there and set `Check for Authentic Theme updates` to `No`. And again, make sure that settings are save.

For me everything you say can not be reproduced (tabs are working and pages load just slightly-lightly slower that in default theme). In case all that I have proposed will not help, all I can do is to install Ubuntu on my test server and then try again.

Let me know more about  points 1 and 2 described above.

**Comment by cmroanirgo** [comment] 2015-06-25 13:12
Yes, the settings save correctly. This is easily checked by doing 'ls -al /etc/webmin/authentic-theme/settings.js' after changing something. When I mention 'spinners', it seems that you imply the big ones that appear in the left/right, which you can turn off. All that does is hides the images and doesn't speed up anything, as far as I can tell.
The spinners I mention are the ones that happen everywhere else. eg When I go to "Webmin Configuration > Webmin Themes", there is a two second or so wait before the first tab appears and says "Current Theme". A spinner appears there & in the page below it.

The 10ms was simply to indicate that my remote server responds quickly and that the problem is not due to latency. (I typically get pings around 0.1ms to my remote server.) Of course local is faster again.
Pings to raw.githubusercontent.com are 0.750-0.900ms, which is pretty fast indeed. Clearly your assumptions are misplaced.

My install setup is nothing special. A blank ubuntu 14.04 (with only OpenSSH). Install webmin. Authentic = unusably slow.

What can I say? I've seen this on every install I've made. I've mentioned in the video 5:18 where it is obviously slow. I have had others mention slow response as the reason why they have moved to other themes.
It is not my configuration, nor my imagination. I would suggest that lots of css and lots of js, and lots of ajax calls are only making UX worse. Adding animations to make things look nice are also adding to the problem.
This is just to load the "Current Theme" page (in just under 2secs):
#CSS files: 10
#JS files: 20
#Font files: 8

(Plus the bug where the select tab upon entering is always webmin on the left, and not the page I specified in settings on the right).

Load up the other themes. Talk to your friends about it and get them to compare.

**Comment by qooob** [comment] 2015-06-27 09:24
> The spinners I mention are the ones that happen everywhere else. eg When I go to "Webmin Configuration > Webmin Themes", there is a two second or so wait before the first tab appears and says "Current Theme". A spinner appears there & in the page below it.

Because the new tab is injected. There is no way not to show it or speed it up. Besides users don't tweak their themes all the time and it's ok as one-time scenario.

>  I've mentioned in the video 5:18 where it is obviously slow. I have had others mention slow response as the reason why they have moved to other themes.

I checked 5.18 and if it feels slow for you, then I would say it is _not_. Yes, it's slower than default theme (by some milliseconds).. but you must understand that Authentic Theme loads a lot of stuff (unlike default theme, not even closely). Speaking of that moment above, where BIND CodeMirror editor is loaded, yes it's a bit slower but again, you get a lot of stuff loaded/initiated. I wouldn't be harsh on that much of a delay.. and it's _nowhere near_ that slow as you say. On the first load, yes agree. But then we're talking about milliseconds. I can't assist you with that.
 
To speed up the first load I could combine all files in one big bundle but that would make any difference on the first start and would result in very little speed-up, which again makes it very unreasonable to do.

> This theme is exceedingly slow to load on each page load. 4.3secs for the home page

To solve this issue go to Theme settings and disable `Check for Authentic Theme updates` and `Check for ConfigServer Security & Firewall updates` by setting its value to `no`. Then you will get proper (as anywhere else on the theme) time for loading System Information page.

 > Change default virtualhost. It always shows the first one in my list and "Default tab after logging" doesnt work.

No and again no possibility for me to confirm this as bug. I just double checked it for you on my machines - result it works perfectly fine for both Webmin and Usermin. Same as for setting up default virtualhost/virtualdomain. All is loaded as expected.

Solutions:
1. Clear browsers cache (less liky to help)
2. Reset theme settings to default and try again right away with setting up default tab and default virtualhost.

In case it still doesn't work, please make a video-screencast with console opened to let me see what is happening.

How did you install the theme?

**Comment by qooob** [comment] 2015-06-30 07:38
..in addition, when you disable `content page loader`, you get nearly the same speed as in default theme (reload the theme or clear browser's cache). You are welcome to disable it, to save extra few milliseconds.

**Closed by qooob** 2015-06-30 07:38 UTC

**Comment by qooob** [comment] 2015-06-30 09:52
However, I will make a new option for you to completely disable all animation on the left menu.
...and also you will be able to disable tabs animation and get back to what you get used to!

It will be there in version 13.10.

Thanks for the ideas!

**Comment by cmroanirgo** [comment] 2015-06-30 23:33
Good luck with this theme. I tried 13.10, and turned off animations. I still wait >4 seconds for the initial load. Webmin tab is still the default tab. I still spend more time 'waiting' than I do 'using'.

I have tried to be as open and as helpful as possible, giving sage advice on why the theme is slow. I have tried to be clear and concise as to the nature of what I'm seeing.
I can only recommend very highly that you do some profiling of the theme, rather than stating "it works for me".

I give up. I shall not bother with this theme anymore.

**Comment by qooob** [comment] 2015-07-01 05:55
I don't say 'it works for me'. On the other hand, you are the only one saying 'it doesn't work for me'. 

I have people on Ubuntu servers and they never complained about this bug. (However, I'll ask them to double check.)

I'm interested in fixing bugs and in improving the theme, in objective ways but not fight costs.

What you're saying can not be confirmed and I can't fix 'something', that works perfectly on 3 different machines.

Giving up or not, its up to you, you shouldn't tell me this. My point is to improve where possible. Make it possible please, like I asked, provide the videoscreencast, of how it works/doesn't work for you so I can see, that tabs are really not working.

Last update, 13.10, imensly increases the speed when all animation is disabled, it _litteraly_ works as fast as default theme.

**Comment by qooob** [comment] 2015-07-01 06:54
To prove my point, please take a look at the following videoscreencasts.

> Videoscreencast of working default tab and default virtual server:

https://rostovtsev.ru/pub/src/authentic/13.10/videoscreencasts/working_default_tab_default_server.webm

> Screencast of showing the speed of Authentic Theme when all animation is disabled:

https://rostovtsev.ru/pub/src/authentic/13.10/videoscreencasts/speed_of_authentic_theme_with_animations_disabled.webm

**Comment by specktator** [comment] 2015-07-01 10:56
@cmroanirgo I use the theme on production env on Ubuntu servers 14.04LTS, the default tab and default vhost are working just fine! 
Note: I re-logged in to see the changes. 
Note2: I do preloading the virtualmin's libraries. I suppose you don't waste the appropriate amount of ram for the convience of your users, if you got any.

**Comment by qooob** [comment] 2015-07-20 09:49
@cmroanirgo The new version 14 will be working a bit faster as I made some  improvements.

I just found out that going to `Webmin->Webmin Configuration->Web Server Options` and setting `gzip` switch to `Use pre-compressed file and compress dynamically`, speeds up the whole process by almost  2 times. 

You can try it yourself to check.

**Comment by mgkimsal** [comment] 2015-07-28 14:41
Been using authentic theme on multiple virtualmins for several months now, never worked.

CentOS 6.3 and 7 as base.

As much as that likely shouldn't be an issue, perhaps it's a contributing factor? (oh, no, I see the OP had this on ubuntu)

I can grant access to a machine exhibiting this behaviour if you'd like to try to debug it.  Also, this has gone on under multiple virtualmin versions (not just one, and I've updated everything) and multiple authentic-theme versions (just tested today on both 13.10 and 14.00)

**Comment by qooob** [comment] 2015-07-28 15:53
> Been using authentic theme on multiple virtualmins for several months now, never worked.

How you managed to use it for several months if it didn't work? What is not working?

**Comment by mgkimsal** [comment] 2015-07-28 16:11
"default tab doesn't work"  The thread issue was (primarily) about the default tab stuff not working, hence my shorthand.  Apologies.

**Comment by qooob** [comment] 2015-07-28 16:12
I see. Alright, if you can provide it for debug, that would be find. However, I will ask you come back with me in 2-3 days as I'm in the mid of re-setting up my server, ok?

**Comment by mgkimsal** [comment] 2015-07-28 16:19
I've used virtualmin for about 8 years, and webmin since... 1999?  2000?  They work, and I'm comfortable in them.  I found the authentic theme about... 4 months ago?  It's nice - I like it.  The default tab stuff has never worked for me.  It's not a huge deal breaker, but wanted to add in that the OP isn't the only one having the issue.  Again, I can give access to someone to dig on the server and see if you can diagnose it.

**Comment by mgkimsal** [comment] 2015-07-28 16:24
sure.  i tried to poke around in the code, but perl's not my strong suit anymore.  was looking for obvious JS bugs that might cause something, but didn't see anything in JS consoles.

This is probably a very easy fix once you can be on a system that is 'broken'.

I've put a video up at https://vimeo.com/134746471 which will be ready to view in about 30 minutes. (free plan queued up for processing!)

@qooob - how about you ping me at mgkimsal@gmail.com when you're ready and I'll either grant access to an existing server or set up a new one.

**Comment by qooob** [comment] 2015-07-28 21:27
Ok, right from the first second watching :) the reason is that Authentic Theme is not set as default theme in global settings. You set the theme as a user in `Webmin->Change Language and Theme` module. It will not work this way.

Please go to `Webmin->Webmin Configuration->Themes->Change Theme` and set Authentic Theme as default. After doing so, you will have nice login screen as on Theme YouTube video presentation.

@mgkimsal Tell me if it works for you?
@cmroanirgo Please, man, also tell how it is for you?

**Comment by mgkimsal** [comment] 2015-07-29 01:37
that seemed to work.  would be useful if it wasn't a requirement, but I've not written a theme, so not sure of the requirements.

**Comment by qooob** [comment] 2015-07-29 06:46
I will check but I think that would no be possible otherwise. Because, theme uses it's on `session_login.cgi` and sets some cookies on init.

**Comment by laugh26** [comment] 2017-11-05 10:36
After install webmin i do see blank page why?

**Comment by qooob** [comment] 2017-11-05 10:37
There are many reasons.

What system are you running it on?

Do you have default port opened?

**Comment by laugh26** [comment] 2017-11-05 10:40
ubuntu 16

**Comment by laugh26** [comment] 2017-11-05 10:40
how do i open default port?

**Comment by qooob** [comment] 2017-11-05 11:13
On Ubuntu you could use:
```Bash
sudo ufw allow 10000
sudo ufw allow 20000
```

You must also make sure that Webmin is running.

What is the output of `curl -L localhost:10000`

**Comment by laugh26** [comment] 2017-11-05 11:18
<h1>Error - Document follows</h1>
<p>This web server is running in SSL mode. Try the URL <a href='https://localhost:10000/'>https://localhost:10000/</a> instead.<br></p>

**Comment by qooob** [comment] 2017-11-05 11:19
Okay, great.

Just type in your browser: `https://localhost:10000/` and hit enter.

**Comment by laugh26** [comment] 2017-11-05 11:19
on vps

**Comment by laugh26** [comment] 2017-11-05 11:19
not on my local computer

**Comment by qooob** [comment] 2017-11-05 11:21
Actually it might not work. Try different.

Find the IP (inet):

```
ip addr show
```

Then type in URL: 
```
https://x.x.x.x:10000
```

**Comment by laugh26** [comment] 2017-11-05 11:27
get this
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 1000
    link/ether 42:01:0a:8e:00:04 brd ff:ff:ff:ff:ff:ff
    inet 10.142.0.4/32 brd 10.142.0.4 scope global ens4
       valid_lft forever preferred_lft forever
    inet6 fe80::4001:aff:fe8e:4/64 scope link

**Comment by qooob** [comment] 2017-11-05 11:29
Try:

```
https://10.142.0.4:10000
```

**Comment by laugh26** [comment] 2017-11-05 11:31
not working

**Comment by qooob** [comment] 2017-11-05 11:32
```
ping 10.142.0.4
```

**Comment by qooob** [comment] 2017-11-05 11:46
Actually, looking at your configuration, broadcast doesn't seem to set correctly.

Ask your VPS provider for network configurations.

Then make sure that you set your server interface correctly.

**Comment by laugh26** [comment] 2017-11-05 12:13
ok
