### ISSUE TITLE
Quotas charts issue

### ISSUE THREAD

**Issue by ThierryMasson** [qooob/authentic-theme#195] opened 2015-06-29 07:27 UTC
Dear,

I Would like to submit this issues with the quotas charts
The right value is correct, but all chart and percent value are totally wrong.
![quotasdefinition](https://cloud.githubusercontent.com/assets/13097715/8402972/e0a66fa0-1e40-11e5-9d9f-78e12eb1b1e0.jpg)
![quotacharts](https://cloud.githubusercontent.com/assets/13097715/8402976/e547ad1c-1e40-11e5-8e69-0a9157065106.jpg)

PS : Execpt this little bug, very good job for your theme !

**Comment by qooob** [comment] 2015-06-29 08:20
Please search through the issues on quotas in theme repo and Webmin GitHub repo. 99.9% the issue is with settings on your side/Webmin. The just parses the percentage output, nothing more. Data is supplied by Webmin functions. There is a fix for you, I think, in closed issues.

**Comment by ThierryMasson** [comment] 2015-06-29 08:30
Dear,

Thanks for your very quick reply, but I have the very last version of 
Webmin 1.760 and the authentifc theme 13.05
I have searched in the GitHub for issue, I have found some reply but for 
previous version of 13.05.

Best regards,


STUDIO MT®

*Thierry Masson*
/Gérant/

Gsm: +32 (0) 479 33 99 67
Fax: +32 (0) 87 22 52 32
thierry.masson@studio-mt.be <mailto:thierry.masson@studio-mt.be>
www.studio-mt.be <https://www.studio-mt.be>

Skype Call : STUDIO-MT <skype:STUDIO-MT> Skype Chat : STUDIO-MT 
<skype:STUDIO-MT?chat>

**Comment by ThierryMasson** [comment] 2015-06-29 18:36
I found what cause the problem:
The chart apparently works only if all sites are configured with "Total server quota" and not on "
Server administrator's quota".
If we set "Total server total quota" for all site, all charts are correct with right percentage.
if we set "Server administrator's quota" for all site all charts are wrong with wrong percentage.

But I work only with "Server administrator's quota" to specifiy the ftp/web site limitation (not on email).
So, how to make it works?

**Comment by qooob** [comment] 2015-06-29 19:03
Upps. It seems to make sence to me now! I will try fixing it by the next release! Please stay in touch and don't close the issue. One more thing: default theme displays correct values?

**Comment by ThierryMasson** [comment] 2015-06-29 19:16
Thanks!
Heuuu; in fact not exactly :-/
![quotachartsdefaulttheme](https://cloud.githubusercontent.com/assets/13097715/8416113/c769ccfe-1ea3-11e5-883f-edee701409ff.jpg)

From the top to the bottom (all set in "Server administrator's quota"):
First quota is : 5 Go (so normaly must be "nearly" full).
Second quota is : 250 MO (I don't understand why he said 3.24 Go : this result is with the mail !)
Third quota : is 50 Mo (same as second 278.7 is with the mail!)
...

**Comment by qooob** [comment] 2015-06-29 19:22
Hmm. I'm afraid that it will be hard then to do. (i will try to figure out though). I will also notify Webmin/Virtualmin developers on that. We'll see!

What is an advantage of using `Server administrator's quota` so I get better understanding? Do you switch that in Virtualmin settings?

**Comment by ThierryMasson** [comment] 2015-06-29 19:25
the difference between "Server administrator's quota" and "Total server quota" is:
"Total server quota": take the total space used by : mail + ftp + db
"Server administrator's quota" : only take "web space" = ftp + db (no mail)

**Comment by qooob** [comment] 2015-06-29 19:27
I see. I will try to figure out! Thanks for pointing out!

**Comment by ThierryMasson** [comment] 2015-06-29 19:27
thanks to you ! Great job !

**Comment by qooob** [comment] 2015-06-29 21:17
How do you enable/disable `Server administrator's quota`?

**Comment by ThierryMasson** [comment] 2015-06-29 21:20
? in virtualmin, chose a server, edit virtual server, quotas and limits :

and you saw both choice (like in my first post, the top picture)

**Comment by qooob** [comment] 2015-06-30 05:36
I also have these settings set:

![screenshot from 2015-06-30 08-31-28](https://cloud.githubusercontent.com/assets/4426533/8424389/8a5e9ace-1f02-11e5-88b5-84205cc84292.png)

And all is working fine!

Can you please read carefully and take a look at this:
https://github.com/webmin/webmin/issues/193

Do you have quotas enabled in `Webmin->Disk Quotas`. Did you re-run `Virtualmin Re-Check Configuration` afterwards?

**Comment by ThierryMasson** [comment] 2015-06-30 06:18
Yes, but "Total server quota" is precisely what I don't want as explained before, because it's a quotas on "all", FTP(web site)/DB AND MAIL....and I don't want mail included in the server quotas (like "Server administrator's quota" works.
I have already read this article, and of course, quotas activated, do several "re-check configuration" and "refresh", and restart webmin....
if fact, each quotas (the right value in the charts) returned in the sytem info is the GROUP quota in state of the USER quota !
If you select "Total server quota (or both)" > that must be "Group quota" to take in account
if you select ONLY "Server administrato'rs quota" > that must be "User quota" to take in account.
So the graph is wrong, because the GROUP quota is set to unlimited (and that's why we have a huge percent value like this and all red bars).

**Comment by qooob** [comment] 2015-06-30 06:35
The problem is, that thee theme has nothing to do with that! :) my theme only takes percentage values supplied by Webmin functions. Please be kind submitting an issue on Webmin page and refering here as well. Don't forget to mention, that it also doesn't work in default theme.

**Closed by qooob** 2015-06-30 06:35 UTC

**Comment by ThierryMasson** [comment] 2015-06-30 06:43
YES that's the conclusion I have made too !!!
Thanks for your support!

**Comment by qooob** [comment] 2015-06-30 06:45
You are welcome. Feel free to come back here in case you need to!
