### ISSUE TITLE
Theme Config on Smartphone / iPhone 

### ISSUE THREAD

**Issue by humantraffic** [qooob/authentic-theme#372] opened 2016-02-04 06:18 UTC
With either recent update to theme or new iOS 9.3 public beta 3,

The theme configure screen won't resize correctly for the browser size. It makes it impossible to change any setting. 

It also sometimes snaps pages back up to the top randomly. 

http://s10.postimg.org/8xrs4nt49/image.png

**Comment by qooob** [comment] 2016-02-04 11:38
Thanks for reporting,

However, I couldn't reproduce your issue on my MacBook Air in Safari. The same it's working fine in Chrome in emulation mode as well. I'm afraid it's iOS beta bug.

In case it's not, please come back to this issue, when you update to the release version of iOS.

I will close the issue for now.

**Closed by qooob** 2016-02-04 11:38 UTC
