### ISSUE TITLE
Theme: Checkbox in the table row, when left-clicked is not toggled

### ISSUE THREAD

**Issue by 7starsone** [qooob/authentic-theme#424] opened 2016-03-17 15:21 UTC
Hello,
I'm on Chrome and search for a cron by description name

then it returns a list of related crons...

ok, but I can't select the cron row

when I click on the checkbox it loads the related cron page instead of just selecting...

thanks

**Comment by qooob** [comment] 2016-03-18 10:01
Hi,

Could you please be kind making video-screencast because however I try I can't reproduce it under any browser/OS?

[Example](rostovtsev.ru/pub/src/authentic/17.64b/Screencast_from_07-02-16_15:17:44.webm)

**Comment by qooob** [comment] 2016-03-18 10:03
You can always use right-click to select the row.

**Comment by qooob** [comment] 2016-03-18 10:04
..but again, I can't reproduce it with the left click. When I click the checkbox with the left click it selects/deselects it and **not enters** the row..

**Comment by qooob** [comment] 2016-03-30 07:07
Could you make the video screencast of how it doesn't work? I can't reproduce it!

I'm working now on another release and I made those rows more clear, when it's clicked and when it's not. I guess that you're just miss-clicking the checkbox.

**Comment by qooob** [comment] 2016-03-31 11:55
Miss-clicking on the checkbox will open the link and make you feel that something is going on. With new release, it will be correspondent cursor on hovering the row, that will be more user-friendly.

Remember, you could always user right click, to select the row. There is no need for clicking checkbox.

I'm closing issue for now and in case it doesn't work for you on 17.80, please provide video screencast.

**Closed by qooob** 2016-03-31 11:55 UTC
Labels: question

**Comment by qooob** [comment] 2016-03-31 21:08
Actually I got it and think it's related to [39974](https://www.virtualmin.com/node/39974).

It should be fixed by 17.80.

Please be kind posting here after upgrading.

**Comment by qooob** [comment] 2016-03-31 21:09
Probably testing it now might already work. Please test and clear the cache after updating the file:

rostovtsev.ru/pub/src/authentic/17.80b/authentic.min.js

**Comment by qooob** [comment] 2016-04-08 12:18
Please upgrade 17.80 is out!
