### ISSUE TITLE
Theme: System Information page load problem

### ISSUE THREAD

**Issue by Gallomanor** [qooob/authentic-theme#659] opened 2017-01-29 16:37 UTC
Server-side OS Ubuntu 12.04LTS
Win10, FF(51) & Chrome (55)

The VirtualMin homepage - sysinfo.cgi seems to load but I can't scroll up, can't Hide New Features or minimise the expanded widgets. I can click on links and they function but I get a "Leave this page. All unsaved data will be lost" message.

Inspect Console gave a few errors. 
![screenshot_012917_043536_pm](https://cloud.githubusercontent.com/assets/1986991/22405884/fa8fad4a-e640-11e6-8d40-cbdfa9f77854.jpg)

**Comment by qooob** [comment] 2017-01-29 16:39
Hi,

How can I reproduce this issue? Did you try _Incognito Tab_? How offen does it happen?

Did you try to clear browser's cache and restart _Webmin_?

**Comment by qooob** [comment] 2017-01-29 16:40
Looking at the screenshot I see that it might be caused by some extension.

**Comment by Gallomanor** [comment] 2017-01-29 16:46
Wow. Quick!

Same in Incognito, Happening everytime. Same when I clear the cache.

Not sure which extension that is but a more recent Inspect with the same problem doesn't include the extension mention:
![screenshot_012917_044614_pm](https://cloud.githubusercontent.com/assets/1986991/22405996/76cd0b5e-e642-11e6-86e1-d52e0c06540a.jpg)

I've recently upgraded to Win10. Before on Win7 never had this problem.

**Comment by qooob** [comment] 2017-01-29 16:47
Did you try the other browser?

**Comment by qooob** [comment] 2017-01-29 16:48
Tried closing/opening the browser?

**Comment by Gallomanor** [comment] 2017-01-29 16:53
![screenshot_012917_044744_pm](https://cloud.githubusercontent.com/assets/1986991/22406009/ac32e80e-e642-11e6-9c7f-ef7d3c16fb4e.jpg)

With added Drop Down details

and here is Firefox.

I closed tab, cleared cache, restarted browser, logged in and same problem:
![screenshot_012917_045247_pm](https://cloud.githubusercontent.com/assets/1986991/22406067/60c3781a-e643-11e6-8f69-7f7264b62c1b.jpg)

**Comment by Gallomanor** [comment] 2017-01-29 16:54
Just tried Webmin on a different server and it is fine.

Guess that means something gone wrong with this installation.

**Comment by qooob** [comment] 2017-01-29 16:55
Hmm.

Can you try:
  1. Changing the theme to Gray Theme, closing browser, than opening again and changing back to Authentic Theme?
  2. Manually reinstall the theme by going to Webmin Configuration -> Themes and install from URL using this link: `https://github.com/qooob/authentic-theme/releases/download/18.32/authentic-theme-18.32.wbt.gz`

**Comment by Gallomanor** [comment] 2017-01-29 16:59
1. I tried changing Theme but it won't accept the button click.
2. Just reinstalled but no change.

**Comment by Gallomanor** [comment] 2017-01-29 17:02
Just rebooted the server, cleared cache, restarted browser. No change.

**Comment by qooob** [comment] 2017-01-29 17:02
Ok,

Do the following using command line:

1. `cd /usr/share/webmin`
2. `mv authentic-theme _authentic-theme`
3. `git clone https://github.com/qooob/authentic-theme.git`
4. `/etc/webmin/restart`

Try again.

**Comment by qooob** [comment] 2017-01-29 17:33
Any luck?

If it works, please send me non-working, previously preserved directory. Just compress it storing permissions on the files `tar -pcvzf authentic_theme_1832_ubuntu_1204lts.tar.gz _authentic-theme`.

**Comment by qooob** [comment] 2017-01-29 17:34
You can find my email address in the comment of `.pl` files in the main directory.

**Comment by qooob** [comment] 2017-01-30 17:28
Any news here?

**Comment by Gallomanor** [comment] 2017-01-30 18:26
Sorry. Child pick up y'day and work all day today. Will try to follow the instructions this evening.

**Comment by qooob** [comment] 2017-01-31 09:49
Any update here?

**Comment by qooob** [comment] 2017-02-01 08:18
:upside_down_face:

**Closed** 2017-02-12 19:09 UTC
Labels: question
