### ISSUE TITLE
recollected never stops spinning

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#838] opened 2017-10-02 21:49 UTC
I now run 19.00 on 4 computers and all 4 have the same issue.
If i press the green update button it show a message `System information is being recollected..` at the bottom of the page but this message never disappear. It continue to spin and the page will never be updated.
![image](https://user-images.githubusercontent.com/5789283/31101016-2d5639ae-a7cc-11e7-8406-4da256ede192.png)

**Comment by qooob** [comment] 2017-10-03 06:49
What is the server OS? What is your browser/OS? What console and Network tabs say?

**Comment by Sopor-** [comment] 2017-10-03 15:56
Webmin is running on `Ubuntu Linux 14.04.3`, `Ubuntu Linux 16.04.2` and two are `Debian Linux 8.0` and I'm running `Windows 8.1` with `Firefox 56.0`. I don't know what you mean with `What console and Network tabs say`?

**Comment by 7starsone** [comment] 2017-10-04 09:42
The issue is on js console:

**Uncaught ReferenceError: messenger is not defined → bundle.min.js?19000:175**

**Comment by qooob** [comment] 2017-10-04 09:44
Confirmed. Will be fixed shortly. Thanks a lot.

**Closed** 2017-10-04 10:59 UTC

**Comment by qooob** [comment] 2017-10-09 18:52
Get latest _git_ version to make it work.
