### ISSUE TITLE
Not loading and Infinite Loop with PaleMoon 27.0.3(x64)

### ISSUE THREAD

**Issue by forofo** [qooob/authentic-theme#655] opened 2017-01-24 01:01 UTC
Following your instructions from yesterday I have updated my browser to 27.0.3 64 bits. 

Still there is the infinite Loop. I've done a reinstall of theme.  I've done a second reinstall of theme + deleting of /etc/webmin/authentic-theme.  

No success. Still there is the loop but not loading theme

I put here the Console errors of my browser:

```
GET https://mydomain.com:10000/index.cgi/?xhr-info=1
200 Document follows 	4,16s	

#----------------------------------------------------------------------------------------
SyntaxError: missing ; before statement
....attr("href")});let DELAY=340,clicks=0,timer=null;$("body").on("click",'.icons-

content...js?1832 (line 6, col 128473)
#----------------------------------------------------------------------------------------
TypeError: window.page.f__g is not a function
...tion fetch_right_pane_favorites(){var a=window.page.f__g(),c=$("#right-side-tabs...

parent....js?1832 (line 6, col 38366)
#----------------------------------------------------------------------------------------
TypeError: g.data(...) is undefined

...]'):0);if(j&&j.contentWindow&&g.length){g.data("easyPieChart").update(n)}}if(l==...
#----------------------------------------------------------------------------------------
	
```

thanks

**Comment by qooob** [comment] 2017-01-24 05:52
Dupe of https://github.com/qooob/authentic-theme/issues/637

**Closed by qooob** 2017-01-24 05:52 UTC

**Comment by forofo** [comment] 2017-01-24 23:01
Still there is this issue. Tested with a clean installation of the browser:

```
SyntaxError: missing ; before statement
content...js?1832 (line 6, col 128473)

TypeError: window.page.f__g is not a function
parent....js?1832 (line 6, col 38366)

TypeError: g.data(...) is undefined
parent....js?1832 (line 6, col 3060)

```
