### ISSUE TITLE
connection error popup appears if I klick to fast

### ISSUE THREAD

**Issue by gnadelwartz** [qooob/authentic-theme#893] opened 2017-11-15 15:55 UTC
Since I'm a impatient guy I often click on a menu point, even the content in the content pane is not loaded. 

Since you implemented the new popup I have the following issue:
If I klick on an other module while e.g. reloading dashboard, the popup pops up.
![bildschirmfoto vom 2017-11-15 16-57-16](https://user-images.githubusercontent.com/4593242/32845842-1c34060c-ca26-11e7-80e7-9090f117f8af.png)

But thats not really a problem, because if the module I klicked on is loaded the popup diasppears.
But what really should not happen is that the menu diappers also and the module uses the  full window:
![bildschirmfoto vom 2017-11-15 16-53-51](https://user-images.githubusercontent.com/4593242/32845667-9c92eb2a-ca25-11e7-8456-d78fdc570ca9.png)

I guess the popup blocks the internal loading of the module an since there is no more content frame its diplayed full window.

**Comment by qooob** [comment] 2017-11-15 16:04
Oh, yeah. That's a draw back.

I'll see how I could fix it.

**Comment by gnadelwartz** [comment] 2017-11-15 16:06
Ah forgot to mentoin: it worked the correct way in the past and as always proxy setup :-)

**Comment by qooob** [comment] 2017-11-15 19:46
It's been fixed in https://github.com/qooob/authentic-theme/commit/20fc9872da3ad21b8e4fb2d454b4d39d6d3f33c8

**Closed by qooob** 2017-11-15 19:46 UTC

**Comment by gnadelwartz** [comment] 2017-11-16 06:49
now i have a new problem. after login menu is displayed, but no content, e.g. dashboard.
if i click on a menu category or on dashboard nothing happens, only the uri changes to https://rrr.de/webmin/#category

#category depends on clicked category name

**Comment by qooob** [comment] 2017-11-16 09:24
Did you get your coffee? :smiley:  Could you please try again? I can't reproduce it.

**Comment by gnadelwartz** [comment] 2017-11-16 17:10
Yes, I had my coffee :-).

When donwgrading to 19.02, everything is working. Update to latest git it's not working again.

try it yourself on mail.rrr.de/webmin

**Comment by gnadelwartz** [comment] 2017-11-16 17:39
searching for a module with the search box above categories and then klick e.g. on firewall is working.
firewall module is displayed and the category opens. In the opend category I can click on any module.

But again opening an other category is not possible.

**Comment by qooob** [comment] 2017-11-16 18:34
I see the source of the issues.

Thanks a lot. It will be fixed along with other found bugs for Side Slider.
