### ISSUE TITLE
Virtualmin Configuration help links load into a new empty page rather than pop a tooltip

### ISSUE THREAD

**Issue by swelljoe** [qooob/authentic-theme#923] opened 2017-12-09 18:38 UTC
In System Settings->Virtualmin Configuration, the help links don't work right; they load into a blank white page, rather than popping up a tooltip. (Other tooltips seem to work, it's just the Virtualmin Configuration page that does this.)

**Comment by qooob** [comment] 2017-12-09 19:33
Hi, Joe.

Confirmed. Will be fixed in a bit.

**Comment by qooob** [comment] 2017-12-09 20:44
Okay, I finally fixed my system after fresh upgrade.

It happened because bind event was destroyed with new new config to accordions feature.

It's fixed on the latest commit.

**Closed by qooob** 2017-12-09 20:44 UTC
Labels: bug
