### ISSUE TITLE
Dropdown list of Domains reset to Webmin in IE11

### ISSUE THREAD

**Issue by pgordemer** [qooob/authentic-theme#99] opened 2015-02-08 15:25 UTC
If you select a Domain from the top dropdown, after the selecting the refresh takes you to webmin and the domain displaying is the first alphabetic domain.

Using Chrome, If you select a Domain from the top dropdown, after selecting the refresh keeps you in VirtualMin with the correct domain selected.

Recap, works as designed in Chrome, error is when using IE11

**Comment by qooob** [comment] 2015-02-23 12:17
Confirmed! Most silly and annoying thing ever, is to debug `IE`.

Did you know that magic happens, if you open _DevTools_ (F12) and then close them - everything works after all!? What do you think that could be??

**Comment by qooob** [comment] 2015-02-24 11:38
Alright, found the reason why it was happening! It will be fixed in the next release in version 10.0.0. Thanks for reporting!

**Closed by qooob** 2015-02-24 11:38 UTC
