### ISSUE TITLE
File Manager: Rename button in action column

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#582] opened 2016-11-15 19:03 UTC
Trying rename a catalog using RENAME button not working....  it's a bug

![c](https://cloud.githubusercontent.com/assets/7549566/20319469/1fdb0cea-ab66-11e6-9f0e-4737240dfd28.jpg)

**Comment by qooob** [comment] 2016-11-15 20:28
Hi,

I just tested it and it's working fine in the latest 18.20.

What is your theme version and the browser?

**Comment by sz00gun** [comment] 2016-11-16 18:39
I have the latest CentOS 7.2-1511, the latest authentic-theme 18.20 and the latest FF and Chrome, and it's not working for me.

Please have a look a screen cast:  http://screencast-o-matic.com/watch/cDXDFxQcH4

Thanks

**Comment by qooob** [comment] 2016-11-16 21:15
Can you login in console under the same username as your login in Webmin and try to `mv folder1 folder2`. I think it has nothing to do with the theme.

**Comment by sz00gun** [comment] 2016-11-16 21:37
It is working under console... but even it;s working when I change the name using menu RMB/Rename - as you can see on the screen cast. 

I don't know..., but I think it is something with the theme, because it worked couple months ago. Also Extract function didn't work recently. (using action column)

It's not a big deal, because we can use RMB/Rename, however I would like to help to make this theme perfect!

**Comment by qooob** [comment] 2016-11-16 21:45
Alright, thanks. I will try to reproduce it and fix it in 18.30.

**Comment by qooob** [comment] 2016-11-19 18:45
Confirmed and will be fixed in 18.30

**Comment by qooob** [comment] 2016-11-23 11:52
It see the reason why it's happening. It will be fixed in 18.30.

Thank you very much for reporting. ;)

**Closed by qooob** 2016-11-23 11:52 UTC
Labels: bug
