### ISSUE TITLE
Bugs in Editor with Firefox

### ISSUE THREAD

**Issue by sn1999** [qooob/authentic-theme#256] opened 2015-10-01 06:21 UTC
There seem to be some Bugs in the Editor (CodeMirror) if you're using Firefox.
1. if you mark some text in FF the background stays white, you can't see what you have selected
In the following Screenshots both times line 101 is selected.

FireFox:
![editor-firefox](https://cloud.githubusercontent.com/assets/14289015/10213930/6526f896-6813-11e5-87ae-74bd9201c9d2.png)

Opera:
![editor-opera](https://cloud.githubusercontent.com/assets/14289015/10213936/74c2a9f8-6813-11e5-827a-d263a303a0e2.png)

This makes selecting a text in FireFox extremly difficult ;)

2. is just a little style bug, as you can see in the FireFox Screenshot, the Textbox is slightly to width in FireFox, resulting in a horizontal scrollbar.

The last Bug seems to be browser independent. If you copy a text via the Mouse rightclick menu (select text -> right click -> copy) and re-paste it, the first char is missing. If you however select the text and copy it with Ctrl+C, the first Char is copied just fine. 

And absolutly off topic, but since this text is a little longer anyway, i want to thank you for your fantastic work, i wouldn't want to use webmin without your great theme anymore :)

**Comment by qooob** [comment] 2015-10-01 06:28
Thank you for reporting a bug and thank you for your kind words.

Yes, I could reproduce this bug in _Custom Commands_ module. However using, let's say Apache or PHP in manual editing gives no problem at all.

I think it's happening because of the way _Custom Commands_ module renders the page. I will keep this in mind and will do be my best to fix it as soon as possible.

**Comment by qooob** [comment] 2015-10-01 06:31
I would also recommend trying [Filemin](https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-0.9.6.linux.wbm.gz) file manager editor with Authentic Theme, which implements great way of editing files, without reloading current page (using background calls).

Have a try if you haven't already. Theme has full support for this module.

**Comment by sn1999** [comment] 2015-10-01 07:01
Yes, seems to be a 'Custom Commands' only issue, just tested the file editor of the Shoreline Firewall which seems to be fine.
Thanks for the Tip with Filemin, i'm already using it and it's awsome, the custom commands file editor buttons are mainly for some other Users, which should be able to edit a specific File (Gameserver config file) without granting them access to all the other files. So i can't really get rid of it.

But back to topic, i look at the html output of the page via the FireFox Code Inspector (Ctrl+Q in FF, Ctrl+Shift+C in Opera), and if i change the 'width: 1305px;' to 'width: 100%;' in the div containing the editor (sadly this one doesn't have an id, but it's classes contain 'CodeMirror' and 'cm-s-default'), the error is gone. But of course i don't know what this would do to all the other editors, since the Code Inspector modifications are only temporary.
Don't know if this helps in any way, but i thought i mention it :)

**Comment by qooob** [comment] 2015-10-01 07:06
Interesting point, thank you! I will take a closer look a bit later.

**Comment by qooob** [comment] 2015-10-07 08:57
It will be fixed in 16.02 very soon. Thanks for reporting!

**Closed by qooob** 2015-10-07 08:57 UTC
