### ISSUE TITLE
Webmin 1.790 brings very slow dashboard refresh

### ISSUE THREAD

**Issue by michel-bosseaux** [qooob/authentic-theme#418] opened 2016-03-07 11:59 UTC
I made the update of Webmin today, and all works. But the dashboard loading (each time, not only the first time) is suddenly very slow (30+ seconds) on all the servers and virtual machines i test it. I think to downgrade Webmin to check if it solves the issue, but i don't like that at all.

**Comment by sdellenb** [comment] 2016-03-07 12:05
In my case (on CentOS 7), it is so slow the nginx proxy produces a 504 Gateway Timeout after 60 seconds. I had to downgrade to webmin 1.780 to be able to use it again.

As there's no error message in /var/webmin/miniserv.log/.error, I'm not sure if it's a theme or webmin issue.

**Comment by qooob** [comment] 2016-03-07 12:06
Hi, 

Yes, I have already reported it. You can replace `web-lib-funcs.pl` from the old version to make it work.

**Comment by qooob** [comment] 2016-03-07 12:08
This is the change that makes things slow:
https://github.com/webmin/webmin/commit/7eec607f863a17c257b0bb449ca2722116b1646d#diff-386f498865bcbec736fad4fb80306aba

**Comment by michel-bosseaux** [comment] 2016-03-07 12:58
I made a new test under ubuntu 15.10 in a virtualbox on Windows 10 ... all works. Not sure to understand why.
I reinstalled Webmin 1.780 on my others servers (not vm), waiting for a better solution.

**Comment by qooob** [comment] 2016-03-07 13:13
Let's wait and see what Webmin dev says. Theme didn't have any changrs in the code recently.

**Comment by qooob** [comment] 2016-03-07 14:12
Another temporary solution is to disable Authentic Theme updates

**Comment by qooob** [comment] 2016-03-07 19:03
It will be fixed in Webmin 1.791 very soon.

**Comment by sdellenb** [comment] 2016-03-08 14:47
I can confirm that 1.791 works fine again on both my servers (CentOS 7).

**Comment by 7starsone** [comment] 2016-03-08 14:57
hello, I'm on CentOS 7...
why can't see other than 1.782 ? thanks

**Comment by qooob** [comment] 2016-03-08 14:59
Reload packages cache and you should see it. ;)

**Comment by 7starsone** [comment] 2016-03-08 15:07
already done before... nothing

**Comment by qooob** [comment] 2016-03-08 15:10
You probably have only Virtualmin repo on. It's updated with some delays usually. Go to http://download.webmin.com/download/yum and download it from console using `wget http://download.webmin.com/download/yum/webmin-1.791-1.noarch.rpm`, then install it with `yum update webmin-1.791-1.noarch.rpm`. Other than that you could wait for Virtualmin repo to be updated.

**Comment by 7starsone** [comment] 2016-03-08 15:16
lol delays, delays....always delays :-D

with PHP FPM it takes forever... PHP FPM... a must have for any server since YEARS :-D how long have to wait for that? please insist with Jamie & co... it's not a "little" matter

**Comment by qooob** [comment] 2016-03-08 15:19
This is why I recommend using Fedora Server. Bleeding-edge and easily updated from version-to-version, using `dnf` (ex. yum).

**Comment by 7starsone** [comment] 2016-03-08 15:21
well, about Webmin update is not so important if not critical... but about fpm yes for sure... ;-) hope they can add support for that really soon...

**Comment by qooob** [comment] 2016-03-08 15:45
I'll let them know! ;)

**Comment by pschoenbach** [comment] 2016-03-25 23:53
1.791 is still much slower than previous versions on my Linux box.

**Comment by qooob** [comment] 2016-03-26 05:15
Probably you have stuck cache. Reload Webmin, if doesn't help, reboot the server.

It was really fixed.

**Closed by qooob** 2016-03-26 05:15 UTC
Labels: help wanted
