### ISSUE TITLE
Theme: Hiding redundant Webmin swtich in Virtualmin mode

### ISSUE THREAD

**Issue by lp86** [qooob/authentic-theme#176] opened 2015-05-27 03:04 UTC
Absolutely love the new theme! Is there a way to hide the Webmin tab? For example so that only the Virtualmin tab is displayed.

**Comment by qooob** [comment] 2015-05-27 07:06
Thank you! In case by tabs you mean toggles on the left top - no, there is no such option - at least so far! What you could do is to login to Webmin as a user and then you will be able to see only Virtualmin. All Webmin modules will be under one, single collapseable menu. If you logged in as root - then both Webmin and Virtualmin tabs displayed.

**Comment by jusfreeman** [comment] 2016-03-05 04:11
@qooob thanks again for your work on this theme, a great contribution

Just following up on this thread, when I'm logged in as a non-root user, Virtualmin Domain admin, I still see 2 toggles at the top ('tabs'): Webmin and Virtualmin.

The links shown under Webmin are also listed in the Virtualmin toggle, they are repeated.

Is this expected behaviour? Or anyway to fix?

![webmin-tab-displayed](https://cloud.githubusercontent.com/assets/10555210/13545548/487da6d0-e2e4-11e5-996d-a269c36b3910.png)

**Comment by qooob** [comment] 2016-03-05 06:41
Hi,

You are very welcome.

It's a good question. :) I also noticed it happening and actually find this redundant.

I think it should be fixed. I will consult Virtualmin team and try removiving it next release.

Thank you for reporting.

**Comment by qooob** [comment] 2016-03-29 08:25
That actually was the intended behavior before some theme update messed vars logic.

Thanks for reporting.

It will be fixed in 17.80.

**Closed by qooob** 2016-03-29 08:25 UTC
Labels: enhancement

**Comment by qooob** [comment] 2016-04-08 12:17
Please upgrade 17.80 is out!
