### ISSUE TITLE
Sending mails in usermin fails with v19.00

### ISSUE THREAD

**Issue by andyhirsch** [qooob/authentic-theme#842] opened 2017-10-04 11:23 UTC
With Authentic Theme 19.00 sending mail in usermin produces following error:
Expecting form-data encoding but got normal encoding

If I revert to 18.49-9 everything's fine again.

**Comment by qooob** [comment] 2017-10-08 17:13
I see the cause of the issue.

Thanks for reporting.

**Comment by alejandromalo** [comment] 2017-10-10 02:59
I'm getting same "Expecting form-data encoding but got normal encoding" error message when trying to restore backups from different sources (local, FTP or S3) and everything works fine if I change theme.

**Comment by qooob** [comment] 2017-10-10 06:06
Those forms have enctype set, with `get` method, which is wrong, I think. changing it to `post` should work.

With the next patch, I'll make sure that all of those forms will always be submitted using `post` method.

**Comment by qooob** [comment] 2017-10-10 08:42
Actually, for the restore page it's not the reason I mentioned above.

**Comment by qooob** [comment] 2017-10-10 10:04
Both of the issues are going to be fixed on the next commit.

I'm surprised that it's actually possible to fix the issue with progressive output and `multipart/form-data`.

**Comment by qooob** [comment] 2017-10-10 12:04
It's fixed in latest git version.

Thank you for reporting, appreciate that a lot.

**Closed by qooob** 2017-10-10 12:04 UTC
