### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by alnork** [qooob/authentic-theme#797] opened 2017-05-24 20:21 UTC
I'm trying to update from the dashboard and it doesn't. Reload the page and continue to indicate that there is a pending theme update...

Authentic Theme 18.48 -> Latest available release 18.49-5
Centos 6.9

**Comment by 7starsone** [comment] 2017-05-24 20:25
https://github.com/qooob/authentic-theme/issues/787#issuecomment-303549882

**Comment by alnork** [comment] 2017-05-24 20:29
thanks!

**Comment by qooob** [comment] 2017-05-24 21:28
Dupe of #787

**Closed by qooob** 2017-05-24 21:28 UTC
