### ISSUE TITLE
Theme: Virtualmin selecting multiple domains for backups

### ISSUE THREAD

**Issue by NettSite** [qooob/authentic-theme#455] opened 2016-04-30 17:55 UTC
Hi, I think I may have a bug for you:

When using [Ctrl][Click] to select more than one virtual domain to backup, the select box behaves more as if one is using [Shift][Click] - all the rows between the two wanted, are selected as well.

I am using Chrome Version 50.0.2661.86 (64-bit) on Fedora release 22.

Just checked Firefox, that works perfectly.

**Comment by qooob** [comment] 2016-04-30 18:03
I'm afraid I can't reproduce it in Chrome 51, with both old (17.84) and new 18.00b (working on it now).

Please have a look. First I used `Ctrl`, than `Shift`:

http://rostovtsev.ru/pub/src/authentic/18.00b/vm_backup_selection_455.webm

Try in incognito mode, maybe some Extensions doing it?

**Comment by NettSite** [comment] 2016-05-04 17:40
Hi Illa,

Sorry to not get back to you sooner. I have the same behaviour in incognito
mode.

I have attached a bad screen recording.

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by qooob** [comment] 2016-05-04 17:41
Where is screen recording? :)

**Comment by NettSite** [comment] 2016-05-04 17:47
I attached it to the email - it was 1.1mb, maybe it got blocked somewhere.



Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by qooob** [comment] 2016-05-04 17:52
Could you upload it to, let's say, Google Drive and share the public link, please?

**Comment by NettSite** [comment] 2016-05-04 18:39
Hi,

See
https://drive.google.com/file/d/0B8CHG1dmi4xjX21XTXdHZ1VGb3pnNmpQOFoxTjh5U0xIS29N/view?usp=sharing

Basically, I click on "Select Data", and then [Ctrl] click on "Drop
Tables".  Everything up to "Create Tables" is selected.

The theme is 17.84

Chrome is Version 50.0.2661.94 (64-bit) on Fedora 23

Best regards,

*William Nettmann*
Cell: 082 309 4007


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by qooob** [comment] 2016-05-04 19:52
I'll take a look in the morning. Thanks.

**Comment by qooob** [comment] 2016-05-10 21:01
I can't reproduce it. Let's expect that version 18.00 will fix it. It has huge number of changes. A lot of things are going to work differently.

I case it's not fixed after update (when it's out), please feel free to reopen this issue.

**Comment by qooob** [comment] 2016-05-18 07:25
Expect this to be fixed in 18.00

**Closed by qooob** 2016-05-18 07:25 UTC
Labels: question
