### ISSUE TITLE
Logo fails to be displayed on login page; Failed to open ../styles.css for writing: Permission denied

### ISSUE THREAD

**Issue by neubreed** [qooob/authentic-theme#220] opened 2015-08-12 23:08 UTC
Sorry if this has been covered but I'm getting the following error when customising the CSS

Failed to open /etc/webmin/authentic-theme/styles.css for writing : Permission denied

Also, how do does one install other extensions like this?:

https://github.com/qooob/authentic-theme-extensions

Thanks.

**Comment by qooob** [comment] 2015-08-13 07:17
You get this error when the file has incorrect chmod/chown. How do you run Webmin? As root user? (Default). Make sure that this file is owned by correct user and chmod it with 660 or 770. It should be alright then. The other solution is to just delete it and try Webmin doing over again, on save action.

How to apply the styles? Just copy/paste the data from those extensions to Webmin Configuration->Themes->Extensions, in CSS part and click save.

**Comment by neubreed** [comment] 2015-08-13 09:27
Hi There .. Thanks for getting back to me.

All the files in /etc/webmin are owned by root:bin including authentic-theme/ What it the appropriate user?

I managed to get it working with chmod 777 but I don't really want to do that.

BTW thanks for a great theme. You're a legend (y)

**Comment by qooob** [comment] 2015-08-13 09:47
Thanks!! :) glad you made it working.

Yes, 777 is not very good idea. If you delete the file, I suppose it should be created with right permissions. Maybe you could try this!? After check on that file permission, what is it?

There will be more tweaks in the future!

**Comment by neubreed** [comment] 2015-08-13 10:22
It seems that I'm the user it prefers .. 

I have a couple of other questions regarding theme extensions:

1. how to I apply theme extensions to Usermin? For now I have made a symbolic link from /etc/webmin/authentic-theme to /etc/usermin/authentic-theme Is that correct? .. 

2. Where does the unauthenticated logo show? .. It doesn't seem to appear on the login screen.

Thanks.. you've done so much work here!

**Comment by qooob** [comment] 2015-08-13 11:27
You're welcome! 

Well. I found that making symbolic link _in some cases_ creates problems. (talking about `/usr/libexec/authentic-theme`).

No you should not create symbolic links for conf files ( `/etc/usermin/authentic-theme`), as it's updated automatically when you save theme settings and when Usermin is installed.

Unauthenticated logo is shown on login screen (first you need to set _Authentic Theme_ as default in `Webmin->Webmin Configuration->Themes->Change Theme` and then log out). If you do so, you will see nice login screen. There, below Webmin sign (as far as I remember), in login box, you will see unauthenticated logo. ;)

Symlinking `/etc/usermin/authentic-theme` directory could be the cause of your issues. Remove symlink and copy files from Webmin config dir to Usermin. After all try saving things only using UI. It should be alright, then!

**Comment by neubreed** [comment] 2015-08-13 21:18
Ok found the issue with the login logo .. There is no definition in the CSS for _logo_welcome so it's using the __logo class properties. There needs to be a class created for _logo_welcome with something ;like this:
._logo_welcome { position: relative; opacity: 1.0 !important; bottom: inherit;}

**Comment by qooob** [comment] 2015-08-14 11:11
Yes, thanks, confirmed! Will be fixed in the next release very soon.

**Comment by qooob** [comment] 2015-08-16 09:13
It will be fixed in Authentic Theme version 15 in couple of days. Thanks for pointing out!

**Closed by qooob** 2015-08-16 09:13 UTC
Labels: bug, help wanted
