### ISSUE TITLE
Network Interfaces - The text is not aligned in 'Return to previous page'

### ISSUE THREAD

**Issue by Sopor-** [qooob/authentic-theme#679] opened 2017-03-16 20:49 UTC
In the Network Interfaces the button 'Return to previous page' is not looking good. It look like this:
![picpick-2017 03 16-14 37 19](https://cloud.githubusercontent.com/assets/5789283/24017845/edb3c30c-0a91-11e7-8dab-3d446b6bacf0.png)
This is how it should look like:
![picpick-2017 03 16-21 42 22](https://cloud.githubusercontent.com/assets/5789283/24017873/0951945e-0a92-11e7-9433-80a1cfa75f4d.png)

**Comment by qooob** [comment] 2017-03-16 20:55
OK, I'll fix it after I finish working on theme configuration for non-root users.

**Comment by qooob** [comment] 2017-03-19 15:57
This doesn't seem to be the theme issue. First of all, I simply can't reproduce it. 

The theme just re-renders data supplied by the server. In case you see this, you must have to provide ways to reproduce it and report it to Webmin repo. It has to be fixed on the server side.

The reason why this is happening is broken output on error page. Jamie should fix it in no time. He would guess very quickly what is missing.

**Closed by qooob** 2017-03-19 15:57 UTC

**Comment by jcameron** [comment] 2017-03-19 17:02
The real issue looks like it's due to an error message appearing in the middle of a table. I'll fix this in the next Webmin release, and also fix the underlying cause of that error.

**Comment by qooob** [comment] 2017-03-19 17:07
Thank you, Jaime! :wink:
