### ISSUE TITLE
File Manager: Extract archive icon not working in action column

### ISSUE THREAD

**Issue by sz00gun** [qooob/authentic-theme#559] opened 2016-10-04 17:29 UTC
I have the latest Virtualmin/Webmin and the latest file manager.

The icon **Extract** not working.
![b](https://cloud.githubusercontent.com/assets/7549566/19084968/6984ad50-8a60-11e6-9e32-ebd4ba2b8bdc.jpg)

Please advise

**Comment by qooob** [comment] 2016-10-04 17:34
Do you have unzip installed?

**Comment by qooob** [comment] 2016-10-04 19:46
By the way, if you click on refresh using right click menu does the button disappear (because I made it work this way - no binary no icon). It appears on the first load but then should be hidden in case unzinp package is not installed.

**Comment by sz00gun** [comment] 2016-10-04 19:58
unzip installed, and uziping is working fine when I press here: 
![c](https://cloud.githubusercontent.com/assets/7549566/19090168/2345523a-8a75-11e6-99be-d6ddf5a8337d.jpg)

so there is no problem with zip linux module

**Comment by qooob** [comment] 2016-10-05 09:48
Ok, I understood. I will check and fix it in 18.20.

**Comment by qooob** [comment] 2016-10-15 17:21
What theme and Webmin version do you have?

**Comment by qooob** [comment] 2016-10-23 12:18
Anyway, I reproduced it. It will be fixed in 18.20.

Thanks for reporting.

**Closed by qooob** 2016-10-23 12:18 UTC

**Comment by qooob** [comment] 2016-10-29 20:33
Version 18.20 is out, please upgrade.

**Comment by alexbogias** [comment] 2018-01-03 08:43
I miss the extract icon in the latest version and i have unzip/zip installed
![unzip-action-missing](https://user-images.githubusercontent.com/1313467/34513843-f71f0c5e-f072-11e7-850d-c0d1bc38c008.png)

**Comment by qooob** [comment] 2018-01-03 09:47
Incorrect MIME type?

**Comment by alexbogias** [comment] 2018-01-03 09:59
Yeah thats what i thought. Thats why i made the screenshot... Thanks a lot for letting me know @qooob
